### ISSUE TITLE
6.0 Regression Testing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1444]
## Testing

Using the spreadsheet below, please complete assigned sections and kick off bugs. 
### [create copy of the testing template](https://docs.google.com/spreadsheets/d/1KPaYP-Lk_PQOX_ayWXllLGIJd9UUjQRX5DafhjdzT7U/copy)

And save it to [Avalon Test Scripts/completed\_tests](https://drive.google.com/drive/folders/0B3iiRmWEFfdYRHpBZ1BTY2lHZjQ) using YYYYMMMDD_lastname as a filename. 

## Bugs found

For each bug found, add a new github issue to [avalon](https://github.com/avalonmediasystem/avalon/issues) and label it "bug". 

Bugs will be triaged and dealt with as necessary. 

## Completed tests
Please put completed test script in [completed tests](https://drive.google.com/drive/folders/0B3iiRmWEFfdYRHpBZ1BTY2lHZjQ/copy)

## Tested On

FILL IN SERVER NAME AND BROWSER INFORMATION HERE

## Example Comment when you're done with a task

Hi all, I section 1 script and notes in: https://docs.google.com/spreadsheets/d/1v-K4NWEPyERabHHCMPADI79P-d1FAu2_fqy_dgfngdI/edit#gid=1730858809

FYI I found bugs #1, #1, #1

## Tasks and assignees

Delete any test steps as necessary if not doing full testing. Assign after the task by using the @joncamer syntax if multiple people will be testing on the same issue.

- [x] 1. Create private collection 
- [x] 2. Web Ingest an item
- [ ] 3. LTI
- [x] 4. Embed
- [x] 5. Batch ingest
- [x] 6. Structural Metadata
- [x] 7. Create group
- [x] 8. Bulk actions
- [x] 9. Search/playback
- [x] 10. Accessibility
- [x] 11. Playback - sticky quality
- [x] 12. Captions
- [x] 13. IP based access control
- [x] 14. Start/end dates for access (Lease)
- [x] 15. Playlists and Items
- [x] 16. Zoom scrubber

**Comment by cjcolvar** [comment]
@joncameron @davidschober I can't tell where this is at.  How much more of this needs to be done?

**Comment by davidschober** [comment]
@joncameron was this a placeholder or did  you already go through a pass a while ago. It looks like we started working on it a long time ago. I think it was completed, and we may want to do a final pass before shipping.

**Comment by joncameron** [comment]
@davidschober @cjcolvar I'm going to use this as a general testing ticket and keep it alive so Matthew can go through a few of these. This one can get closed out early next week probably, and then we'll write a new one for the final testing pass.
