### ISSUE TITLE
Have playlists use stream refresh rather than reload page on playback

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1467]
### Description
Auto-advance between items in a playlist currently utilizes a full page reload with a URL pointing to the next items, resulting to very long load times for lengthy playlists.

### Tasks
- [x] Refresh the stream
- [x] update the markers on the player
- [x] update the info section on the bottom
- [x] update the right hand column's now playing
- [ ] reload entire page when switching media types (audio and video)
- [ ] get autoplay working again #1469

Original story: #1354
