### ISSUE TITLE
As a User I Want A System for Categorizing and Organizing Playlists

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1538]
## Description
As a user, I want to categorize and organize my playlists for each of searching and sorting. 

### Use Case
For users with tens or hundreds of playlists, navigation can quickly become cumbersome. Besides the name of the playlist, there is no way to order or arrange lists of playlists. For a faculty member who wants to share a subset of playlists with students of a particular course, for example, there would have to be a naming convention used in the name or some external means of organization for them to be in one place.

#### Tags
In an initial planning meeting tags were decided upon as the means to categorize playlists for the purposes of searching and sorting.

Tags would be user-defined and allow a single playlist to “belong” to multiple courses, topics, etc.
Allowing arbitrary tags to be placed on a playlist will aid in searching and sorting. For example, a faculty member may tag a number of playlists with the tag 'MUS 152', indicating that playlists with that tag correspond to a particular course.

Users can add one or more _tags_—descriptive strings— to playlists in the playlists view. These tags appear in their own column. A search bar is available to search only for specific tag

### Done Look Like
Initial design work is done and circulated to key users for feedback before implementation.

### Tasks
 - [ ] Add tags to the Playlist Model and corresponding unit tests
 - [ ] Add tag list to the playlist edit page
 - [ ] Create tag editing field to be re-used whenever someone wants to edit tags
 - [ ] Add tag list and edit button to the playlist index page

**Comment by mcwhitaker** [comment]
@joncameron I think this Epic should be rephrased. What the user wants is a better/faster/easier way to find and navigate to a playlist among numerous playlists.

**Comment by gfitzwat** [comment]
Rough concepts...

![1538-artboard-1](https://user-images.githubusercontent.com/7095544/27200798-3b1c903a-51e9-11e7-8e9b-0e3c78af3e7b.png)
![1538-artboard-2](https://user-images.githubusercontent.com/7095544/27200808-41edd540-51e9-11e7-89d3-6aae51610006.png)
![1538-artboard-3](https://user-images.githubusercontent.com/7095544/27200815-47ce5926-51e9-11e7-9bb0-7ef453fec950.png)

**Comment by mcwhitaker** [comment]
@gfitzwat Thank you, Matt! I think we need the design of how to filter playlists using the tags; I imagine that is next on your list.

@davidschober -- @joncameron and I were a bit hesitant about using colored tags. What does NU prefer? I think that @gfitzwat did a good job at picking the tag colors but my hesitation stems from the fact that the colors may clash with some branding palettes. We can move away from colors if we prefer to play safe. Or we could make the 6 colors configurable if that is easy, and then each implementation could decide on the colors to use that would would work with their branding.

FYI - I asked @jwd and he does not have a preference one way or another. 

We may talk about the other pieces of this design, but I wanted to start the conversation on colors now.

**Comment by gfitzwat** [comment]
@mcwhitaker  Here's what I was thinking about filtering the playlist by tags
![1538----tagsartboard-4](https://user-images.githubusercontent.com/7095544/27455713-430af952-576c-11e7-8bef-bbbca5f45ddb.png)

**Comment by mcwhitaker** [comment]
@joncameron Have you had the chance to talk to anyone about whether selecting multiple tags implies an AND or an OR? In other words, will more tags in the filter narrow down the search or broaden it? I think this may affect the design. For the Facets, more criteria narrows the search (AND).

@gfitzwat If you have hundreds of playlists, the tag you need may be in a playlist way down on the list of playlists. Unless I am misinterpreting what you are saying, this does not eliminate the need to search by scrolling down and carefully looking.

**Comment by gfitzwat** [comment]
@mcwhitaker, good point, I guess we could sort tags to on the table, and I envisioned the user being able to search box to filter the results by tag name as well. Would it be worth it to add a select box and allow the user to filter on the tags something like...
![1538_artboard-5](https://user-images.githubusercontent.com/7095544/27484663-0b481068-57f8-11e7-8eaa-208fb7a74168.png)

**Comment by mcwhitaker** [comment]
@gfitzwat Thank you, I think the filter by tags tool is important there!

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners With the sorting and filtering now in place for playlists, do we still want/need tagging?

**Comment by mcwhitaker** [comment]
@cjcolvar sorting and filtering were not meant to be replacements for the tagging. If we want to propose this, we need to go back to the users. They actually said explicitly that if they had to choose between these, they would want the tagging instead of sorting and filtering.

**Comment by davidschober** [comment]
DECISIONS:

Color should be ignored. We should add a class and allow that to be something that can match the institutions branding. E.g. light blue, grey, etc. The default should be a light grey.

Description should be ignored for now. We will follow a standard design pattern for "tags" .  It is just a free floating label. 

Leah can redo the mockup/ prototype.

**Comment by Karthikeya212** [comment]
I have added some lists with tags and some without, when I tried sort on Tags column, it has blank tag cells on above and below the filled cells.
![image](https://user-images.githubusercontent.com/25850972/31502543-670c8754-af3b-11e7-803d-af1f6a6c8800.png)

**Comment by Karthikeya212** [comment]
The "Filter" option looks like doing a wildcard search rather than the exact string for tag.
![image](https://user-images.githubusercontent.com/25850972/31502968-67561850-af3c-11e7-8d4a-772317dc80e3.png)
