### ISSUE TITLE
Update manual instructions to support RHEL 7

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#1630]
### Description
Recently we have many people coming to Avalon with CentOS7 and be frustrated not being able to install it. Since RHEL 6 is near the end of its life, we should have support for 7 ASAP.

### Done Looks Like
Manual instructions for installing Avalon on RHEL7 are written on the wiki and ready for potential installers to use.

### Tasks
- [ ] Get clean 7 VirtualBox
- [ ] Figure out build instruction for ffmpeg 
- [ ] Change all RHEL6 to 7 commands (yum, service)
- [ ] Does SElinux need disabling?
- [ ] Run through and update the rest

**Comment by joncameron** [comment]
Still relevant or already taken care of? This was ASAP 6 months ago.

**Comment by phuongdh** [comment]
It's still relevant
