### ISSUE TITLE
Investigate whether hidden leased items are showing in search results

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1758]
## Description 
This is now an investigation ticket; as per the comments this just needs to be verified to make sure the bug is resolved. If not, we'll document and create a new ticket if necessary.

### Original Description
Hidden lease items are showing up in search results. As part of our rollout of Avalon 6.x we initially decided to call this a known issue (edge case). For now we should reinvestigate simply write it up as a known issue.

### Steps to reproduce the behavior

1. Open two windows with spruce system, and login with a Manager and a avalon User.
2. Using Manager window, add lease for the user for an Item. Also click the option "Hide this item from search results" and save the changes.
![lease item hidden](https://cloud.githubusercontent.com/assets/25850972/26001276/d2df481e-36f9-11e7-917b-b17145027cf5.PNG)

3. Make sure the item is published.

4. Go to the User window and search for the item.
![lease item search](https://cloud.githubusercontent.com/assets/25850972/26001281/d5d46cca-36f9-11e7-9086-67414f4a6adc.PNG)

## Tasks

- [ ] Verify this is still an issue
- [ ] Investigate why hidden lease items show up in search results (if necessary to refresh memory)
- [ ] Document why this occurs, and that it is a known issue in technical docs here: https://wiki.dlib.indiana.edu/display/VarVideo/Known+Issues

**Comment by carrickr** [comment]
@davidschober Do you know which one this is a copy of?  I wasn't able to figure out one where.

**Comment by davidschober** [comment]
@carrickr I don't. I'm trying to flesh it out, but it was from a while ago. @joncameron can you get a screenshot and add it to this issue?

**Comment by davidschober** [comment]
oh, the copy label does not mean duplicate but "writing" as in copyeditor. @carrickr

**Comment by mcwhitaker** [comment]
@Karthikeya212 Could you please try to reproduce and add the _steps to reproduce_  to the description of this ticket?

**Comment by mcwhitaker** [comment]
@Karthikeya212 The steps are in #1686. It looks like we closed #1686 because we could not reproduce it. I wonder if this is still a problem.

**Comment by davidschober** [comment]
I think this should have been closed at the same time. @Karthikeya212 if you can give it one more shot, and assuming we can't reproduce, feel free to close.

**Comment by cjcolvar** [comment]
@davidschober @joncameron It looks like we need a story to update the Known Issues page for 6.x

**Comment by joncameron** [comment]
@cjcolvar @davidschober Thanks Chris, I've created #1947.

**Comment by Karthikeya212** [comment]
Just to add on, this issue is not seen if the user/group is given special access without dates specified. In this case the item is hidden properly for the user/group.

**Comment by joncameron** [comment]
Closing this stale issue; will create a new issue when the problem is seen again.

**Comment by cjcolvar** [comment]
I think we should make a new ticket for this bug so we don't forget about it.
