### ISSUE TITLE
Write Linux Instructions for R6 Dev Environment using Docker

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1761]
### Description
There are currently instructions on setting up a dev environment in the wiki of our main Github repository for macOS and Windows. Instructions for setting up a Docker container environment for R6 development on Linux also need to be written. These will probably be a rewritten version of the Mac instructions.

### Parent Issue
#1704

### Done looks like
As a new user using linux, I want to spin up an avalon dev environment with Docker.

### Tasks
- [ ] Create a new wiki page under the avalon repo for Linux Docker instructions; most likely copying the [macOS instructions](https://github.com/avalonmediasystem/avalon/wiki/Configuring-an-OS-X-Development-Environment-With-Docker-Containers) into that page wholesale and rewriting with that as the base
- [ ] Rewrite [network hacks from MBK if necessary](https://github.com/avalonmediasystem/avalon-docker/blob/development/networking.md) 
- [ ] Documentation is tested and validated by a developer other than the one who created the instructions

**Comment by davidschober** [comment]
stale, we've been  running docker for a long time.
