### ISSUE TITLE
Metadata: Units for Collections

### ISSUE THREAD

**Issue by jenyoung** [avalonmediasystem/avalon#1763]
We could use Admin Sets in Hyrax for Collection Units. Needs investigation.

## Description

We would like to have unit names be recorded as URIs. Either the URI needs to be entered by the user, or some type of controlled vocabulary needs to be pulled. 

In the first iteration it is OK if a user puts in a URI manually as long as we can get the string from the vocabulary. 

The backing data source would be up to the institution and how they manage the units. Some may be in LC. Some may be local objects. The institution could use any controlled  vocabulary source. We could 

## DONE Looks like

Units are mapped to http://id.loc.gov/ontologies/bibframe/heldBy and values stored for units are URIs (preferably from authorities that already exist, like LCNAF). Users should still see text label for unit (unit name).

## Tasks
- [ ] Update predicate used for units to bfheldby 2.0
- [ ] Add validation for URI value of bfheldby
- [ ] Changed example controlled vocab to use key/value pairs for units (label/uri)
- [ ] Update controller code to handle key/value pairs
- [ ] Document migration

## Notes

The units are not managed in any kind of 

The property that needs to bused is the BF2.0 rather than the 1.0 (currently)

Collection (AHEYM) - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/rj/43/04/57/rj430457n
http://bibframe.org/vocab/heldBy is from BF1.0, not BF2.0 (http://id.loc.gov/ontologies/bibframe/heldBy)
using BF2.0, value needs to be URI
recommendation was to use BF2.0 term, but either way expected value is a URI, not text

Units need to be URI values to use bf:heldBy correctly. Hyrax does not have a built in solution.

Fixes #1606

**Comment by davidschober** [comment]
it looks like this collection is deleted, @jenyoung or @jlhardes can you get another example.

**Comment by jlhardes** [comment]
You can try this one now for AHEYM: http://mallorn.dlib.indiana.edu:8984/fedora4/rest/k9/30/bx/08/k930bx081

**Comment by davidschober** [comment]
is it mapped correctly now? I see this:


ns003: heldBy
Archives of Traditional Music
ns004: default_hidden

**Comment by davidschober** [comment]
I'm a bit confused on the work necessary for this one. Is this a controlled vocabulary each institution implementing Avalon would need to define?

**Comment by jlhardes** [comment]
Yes, units need to be represented as URIs to work with the heldBy property (whether it's in BF1.0 or BF2.0). This can be a value from LCNAF or any other linked data source if there is an authorized form of the unit's name available as linked data or it might need to be a locally-created object that can then be referred to via URI. That's up to the institution.

ns003:heldBy in the example above is still the BF1.0 ontology which is no longer supported. The BF2.0 property for heldBy is what should be used instead (http://id.loc.gov/ontologies/bibframe/heldBy).

**Comment by jenyoung** [comment]
I agree -- A side issue, can we control the display of the units?  Example -- NU Archives has a LCNAF form which is 
**Northwestern University (Evanston, Ill.). University Archives** with a URI of http://id.loc.gov/authorities/names/no2016011576

However, we currently have this display as **Northwestern University Archives**. I think we would want this to continue to display this way.

**Comment by davidschober** [comment]
At some points we will have a controlled vocabulary YAML file that is locally. There will be a display value and a URI. This is not going to be handled in migration. It is a relatively small  set that will...

**Comment by davidschober** [comment]
@jenyoung @jlhardes after reading through these notes from a while ago, it looks like we decided this was a local migration issue? Can we go ahead and close?

**Comment by jenyoung** [comment]
@davidschober bf:heldBy needs to be implemented and needs to have URIs and labels. The value of the URIs and labels can be defined locally.  Avalon can provide a YAML file  and documentation for implementation.

this is the property: http://id.loc.gov/ontologies/bibframe/heldBy

**Comment by jenyoung** [comment]
this can be done as part of the general reworking of descriptive metadata to RDF mappings in 7.0

**Comment by jenyoung** [comment]
related or duplicate issues #1287 #1286

**Comment by jenyoung** [comment]
We could use Admin Sets in Hyrax for Collection Units. Needs investigation.

**Comment by joncameron** [comment]
To be used as the Epic—best describes the entirety of this work.

**Comment by joncameron** [comment]
In essence: Avalon 7 needs to use the bfheldby for Unit, property needs to be a URI; migration path will need to be written for 6 to 7.

**Comment by jlhardes** [comment]
bf:heldBy property should be added to AdminSet properties in Avalon 7/Hyrax with URI as value

**Comment by davidschober** [comment]
Sorry getting back to this now. This doesn't feel like an epic. @joncameron, can you rewrite it and move it into refinement for pointing/ I'd like to keep our epic column to be only issues that have children that are being worked on in the current cycle. 

cc: @jenyoung, @jlhardes
