### ISSUE TITLE
Ensure Variations Playlist Import Fails Gracefully

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1764]
## Descriptive summary
When a user imports a Variations playlist file that contain Variation IDs which are not mapped to Avalon IDs, a generic error page is returned.

## Expected behavior
The standard error page for Variations playlists that have problematic items appears and alerts the user to the items that could not be found. (I believe this is  avalon/app/views/playlists/import_variations_playlist.html.erb)

## Actual Behavior
A generic Rails error page appears.

### Done Looks Like
Variations playlist import is fixed so that it fails gracefully—meaning that it returns the standard error page for Variations imports instead of a 404 page.

see #1674 for reference and discussion

###  Tasks
- [ ] Catch any exceptions that are thrown during import
- [ ] Decide what to show user on error page (stacktrace, thrown exception, generic text)
- [ ]  Log exception
- [ ] Return to error page for Variations imports with error message

**Comment by davidschober** [comment]
@bkeese or @cjcolvar is this still an issue or can this be abandoned?

**Comment by cjcolvar** [comment]
From the code it looks like this may be done.  Someone could try to reproduce it or we could just abandon it.

**Comment by mcwhitaker** [comment]
@cjcolvar In the original ticket, Brian does say that the code implies that things are handled gracefully, but that something was probably not working as expected as we were getting the error page.

@davidschober @joncameron I don't recall this being worked on.

**Comment by davidschober** [comment]
OK. I think the goal is clear. We will try to recreate it and fix if it bugs out. @cjcolvar do you want to take a stab at pointing?

**Comment by joncameron** [comment]
This should get tested in 6.x before we proceed with it. I wrote this for 5.x and it should be verified by Karthik in 6.x before we proceed.

**Comment by mcwhitaker** [comment]
@Karthikeya212 Please note comment by @joncameron on this ticket requesting that you test this in 6.x

**Comment by joncameron** [comment]
Karthik has tested this and it is a problem in 6.x and should be fixed there.

**Comment by Karthikeya212** [comment]
Just to note, if there is a new page created to display proper error message, make sure to check the below issue as well.

After the user is navigated to the error page, if he clicks back button on the browser and either (i)refreshes the page or (ii)clicks on Playlist link which eventually refreshes the page, a success message is displayed on the page though the playlist import failed.

![variations playlist import issue](https://cloud.githubusercontent.com/assets/25850972/26216754/39029726-3bd3-11e7-8b3c-38f2fdd2f7be.PNG)

**Comment by bkeese** [comment]
Exceptions aren't being thrown, an we're not finding errors on bad playlist_items or clips. Errors on those items don't exist because we are not calling valid? on them first.
