### ISSUE TITLE
Create Avalon Work Type

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1773]
### Depends On
Decision from #1824 about whether to implement a new work type or not.
--
We've made the decision to create an AV work type for Avalon 7, so this issue now represents creating that work type.

This is broken out in:

#1821
#1822
#1854
## Done looks like
NOTE: This doesn't include actually playing the video.. We will focus on robust descriptive metadata to drive a full-featured Avalon like experience. Controlled vocabs aren't going to be taken on this issue. The goal is to replicate the descriptive metadata fields in current Avalon. This will take a lot of work from @jenyoung @jlhardes.

- [ ] a content-type (or one each for Audio and Video) is added augmenting technical and descriptive metadata (if necessary) From #1808 #1772
- [ ] content type allows for technical metadata
- [ ] Forms allow ingestion of augmented descriptive metadata
- [ ] Front end displays metadata

Note this extends work done in #1854

**Comment by joncameron** [comment]
We don't know if need an Avalon work type or if the generic work type is enough. If the generic types are enough to drive our proof of concept player, we can come back and think about what an A/V work type is that would be different in Hyrax and if we actually need one.

**Comment by davidschober** [comment]
We need to know a little more about how the player will be implemented. 

julie: There will be technical metadata that needs to be incorporated. 

val: it will be some time of media work type.

**Comment by carrickr** [comment]
I think the 5 on this might actually be a bit low as I work on it in Hyrax.  The process itself is not complex, it's more like going to the DMV and just needing to fill out a billion forms.  None of them are two hard, but you're still going to be there all day.


Ideally what we want to do is something along the lines of using the generic work type generator and templates currently in Hyrax and then using Thor to inject on top of them.  So this involves updating the model, show, and forms within in Hyrax and then dropping in spec tests as well.  We can do our own generator and templates, but it isn't particularly DRY to do it that way.

I would vote for breaking this into having one ticket for the model, which is probably a 5, and then a ticket each for the show and forms that are both 2 or 3s.  Since we also need to do specs with each of them, etc.

This also might be a good swarm topic where I can show what I have.

**Comment by mcwhitaker** [comment]
@carrickr I would be very interested in the swarm. And I don't have a problem with breaking the story.

**Comment by mcwhitaker** [comment]
Depends on decision from #1824

**Comment by davidschober** [comment]
@carrickr and @cjcolvar is any more breaking out necessary? I'd like to get this into the next sprint so we can start to make things a bit more real.

**Comment by cjcolvar** [comment]
I'm having problems tracking exactly where this is at.  Looks to me like this ticket is the epic and #1821 and #1822 are the broken out tickets.  If that is the case it seems like we would need a ticket for the form and another for any search related changes.

I think it would be good to have a ticket writing/refining session on this epic per the new process.  Maybe we could do this tomorrow during backlog buddies?

**Comment by davidschober** [comment]
I agree. It seems to me we might want to use Hyku's image content type as a model.

**Comment by davidschober** [comment]
@cjcolvar and @joncameron this is represented in other, smaller issues, so this can be abandoned now correct?

**Comment by cjcolvar** [comment]
@davidschober I think the questions is do we want to have an issue which tracks an epic or have that be captured purely by labels?

**Comment by davidschober** [comment]
I think it's OK if a story is broken into smaller and smaller tasks to close out, otherwise we may end up with a few orphans. Especially as stories often change as we get into the nitty gritty (like this one did). If it's represented by the others, we should be OK. (although we should remove the points).

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#93
