### ISSUE TITLE
[EPIC] Implement  endpoint for hyrax-driven IIIF-AV API

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1775]
This is an Epic for work in #1856 and #1857

## ISSUES

#1857
#1856

## DONE looks like

The goal is to have a documented approach to implement and write any issues #1755, #1694. When this is done we will have a good idea of what our urls will look like. Per Chris' comments below, hyku (and hyrax) create a iiif 2.0 presentation manifest e.g concern/generic_works/[PID]/manifest.json. 

- [ ] Approach for IIIF-AV endpoint is documented see notes below
- [ ] Verification of data necessary to drive **basic** POC (a video that has some metadata and can play)
- [ ] does iiif canvas need be referenced from the manifest to fall in line with hyrax pattern (needs digging).
- [ ] write up issue on what needs to occur to extend these libraries.
- [ ] extract IIIF manifest work from hyku into plugin

**Comment by cjcolvar** [comment]
Hyku's IIIF endpoint is here:
https://github.com/projecthydra-labs/hyku/blob/master/app/controllers/concerns/hyku/iiif_manifest.rb
which uses iiif-manifest to actually construct the manifest:
https://github.com/projecthydra-labs/iiif_manifest/
starting here in ManifestFactory:
https://github.com/projecthydra-labs/iiif_manifest/blob/master/lib/iiif_manifest/manifest_factory.rb

**Comment by davidschober** [comment]
so we might be done.

**Comment by davidschober** [comment]
I think this might take some upstream changes to account for video canvases.

**Comment by joncameron** [comment]
Our approach yet to be figure out—sandbox vs. contributing to plugin directly.

**Comment by joncameron** [comment]
2 pieces of work: committing to the iiif-av manifest gem (support for iiif-av manifests), and extracting hyku's iiif manifest MVC into a plugin for hyrax.

**Comment by cjcolvar** [comment]
Discussions on slack revealed that there is interest on porting the hyku code into core hyrax and some effort has already been applied by Matt Critchlow (UCSD) and Thomas Scherz (Cincinnati).  I said we would let them know when we start work on this.  Matt mentioned that they might be able to apply some dev effort to this.

**Comment by davidschober** [comment]
For proof of concept we can use static manifests.

**Comment by davidschober** [comment]
@cjcolvar This needed your input for pointing. Feel free to size and/or discuss.

**Comment by cjcolvar** [comment]
@davidschober I'm not entirely sure what this story's goal is now so I can't size it.  Are you saying in your last comment that the IIIF AV endpoint should serve up static manifests?  Is your thought that we would still pull in Hyku's endpoint code but only return a static manifest (static as in the same manifest is returned regardless of the query)?

**Comment by davidschober** [comment]
@cjcolvar The static comment was just saying that for POC we can use a static manifest. The work here is to define how we will implement a IIIF endpoint (it was written before we knew of the existence of hyku's manifest gem.

**Comment by davidschober** [comment]
Abandoning... this was broken int #1854 and #1856

**Comment by davidschober** [comment]
#1857 too.
