### ISSUE TITLE
Example streaming manifests work in IIIF POC Player

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1777]
## Done looks like

An avalon content type can be streamed using a generic streaming interface currently used by the Avalon project. The POC should work both in Wowza and AWS. It should target HLS and DASH derivatives. 

- [ ] Example manifests can work HLS and Dash streaming from a streaming solution
- [ ] Make a wiki page to start to flesh out decisions
- [ ] The IIIF consumer is playing from streamers servers in HLS and DASH

### Technical issues referenced:

_fill in references to any technical issues_

depends on

* spec #1775 
* end point design #1694

**Comment by davidschober** [comment]
Content does not need to be mpeg-dash.

Jamie: All we need is a URL, as long as the player can play it.

**Comment by carrickr** [comment]
This is way underpointed and needs significant thought to flesh this out.  This feels more like a parent issue for all streaming related issues.  Removing the size.

**Comment by davidschober** [comment]
Thanks @carrickr. This was pointed assuming that the IIIF manifest needs a URL to point to. Considering that, can we not put a pair (or triple) of video derivatives in s3 and use cloud front as our POC streamer? Currently @adamjarling and @little9 are pointing at a statically parked video/audio.

**Comment by adamjarling** [comment]
@davidschober @joncameron Should this story be re-evaluated now that we're a little further down the road, and having the MediaElement 4 / HLS discussions?   

The current IIIF Player's sample manifests are all hosted on IU's servers.  Is this story just a test that the IIIF Player can play from different servers, different file types?  If so, we could just mock up a sample manifest and point the source URL to a video on NU's AWS environment?

**Comment by davidschober** [comment]
@adamjarling @joncameron  I think this issue can be abandoned. We went a slightly different direction and have accounted for the items in different ways. I've removed the points and closed. Reopen and argue if you feel strongly.
