### ISSUE TITLE
Stand up minimal Avalon 6.x in AWS

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#1780]
### Task List
- [x] Fedora in ECS
- [x] Solr in ECS
- [x] Avalon in ECS
- [x] Redis #6
- [x] RDS completed with #1720
- [ ] Elastic Transcoder
- [ ] S3 for masterfile/derivative, no dropbox
- [ ] CloudFront
