### ISSUE TITLE
define metadata  needs for Avalon in hyrax

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1808]
## Description

In order to create a work type (or verify that a Generic Work type will fit our needs) we need to have a list of descriptive metadata we need for Avalon in Hyrax. This can build off the the work done in mods--> rdf working group, etc. 

## Done looks like

expands on #1772.
- There is a metadata comparison document
- Recommended changes to Hyrax Generic Work type and/or additional metadata fields needed for Avalon work type are documented
- Required fields are documented

## Tasks
- [ ] Metadata field comparison btw Avalon, MODS and RDF group, and Hyrax is complete
- [ ] Discussion of required vs non-required fields
- [ ] Metadata field changes needed for Generic Work type in Hyrax are documented
- [ ] Additional metadata fields needed for Avalon work type are documented
- [ ] investigation of plum (or other complex) hyrax/sufia driven tool if necessary.

**Comment by davidschober** [comment]
@jlhardes and @jenyoung everyone seems to be moving pretty quickly. I wonder if we can go ahead and document what we think we'd need to completely describe avalon works .

**Comment by jenyoung** [comment]
@jlhardes and i have already planned to meet after standup on friday. @davidschober

**Comment by joncameron** [comment]
There's a conversation to have about descriptive metadata. 
Question: What is it we want to show as far as technical metadata?

**Comment by jenyoung** [comment]
this will be part of the Avalon "gem"

**Comment by jlhardes** [comment]
Descriptive metadata questions: do we need to bring descriptive metadata into Hyrax as RDF properties to begin or is it better (and possible) to start with descriptive metadata as MODS XML files?

**Comment by cjcolvar** [comment]
I think it would be easiest to start off with RDF only if we could get away with that.

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#97
