### ISSUE TITLE
Discuss use of Admin Sets/ Avalon Collections

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1809]
## Description

As we move into a hyrax environment, several core concepts are changing. The team needs to do a deep dive and document how we plan to use Admin sets and Workflows. Display sets are currently in flux, but we should gain a basic understanding of how those might work. 

* [Current High-level docs -- from LDCX](https://docs.google.com/document/d/1oCVnyzamH1sD3mSaqPooknfRTDYKYAsAdEx61hBm6v4/edit)

## Done looks like

A plan for Avalon's use of Hyrax Admin Sets is created, documented and stories written for implementing plan.

## Tasks

- [ ] Read the current high-level docs -- update if these are out of date. [Documentation](https://docs.google.com/document/d/1oCVnyzamH1sD3mSaqPooknfRTDYKYAsAdEx61hBm6v4/edit)
- [ ] Discuss admin sets and display sets etc
- [ ] Document how we plan to use Admin sets in a "default" Avalon install (as workflow holders, as high-level collections, etc)
- [ ] Write issues for work needed to use Admin sets / Display sets to govern workflow and display.

**Comment by carrickr** [comment]
We can probably do this with a subset of the team that knows Hyrax initially to determine how we'll do it and then present notes/a proposed pattern back to the larger team?

**Comment by mcwhitaker** [comment]
@carrickr What you propose is more or less how some of us are thinking we may work with Epics. Tomorrow's conversation on process might get us to a consensus on how to go about Epics.

**Comment by davidschober** [comment]
@carrickr that makes sense to me. (Per @mcwhitaker let's bring this up tomorrow too).

**Comment by cjcolvar** [comment]
This should now include the Collections Extension work (currently being tested on nurax) which will be released soon.

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#105
