### ISSUE TITLE
Bibimport Leaves Old Data In Place

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1837]
### Description

When the bib-import button is pressed, the record is saved at that point. If a new bib-import is performed, then only fields with data will be imported and the other fields from the old import will remain with the old content.

### Done Looks Like
- Information from a previous bibimport shouldn't stay in place on another bib import.
- We should throw a warning with an OK that says "Note, this is going to replace all metadata. 

## NOTE

This is scoped for everything _except_ for other identifiers.

### Tasks
- [x] Don't overwrite existing other identifiers, de-dupe when importing.
- [x] Remove previous bib_id from other identifiers, if it exists
- [x] De-dupe imported languages
- [x] Add confirmation to bib import button
- [x] Document change

**Comment by davidschober** [comment]
Scope the fix to replace **all old fields** other than Other Identifiers. 

We will break out Other identifiers into a separate story

**Comment by jlhardes** [comment]
Other Identifiers handling for bib import covered in #1950

**Comment by bkeese** [comment]
Text for confirm button "Note: this will replace all metadata except for Other Identifiers."

**Comment by cjcolvar** [comment]
I tried this out on mallorn and the only fields I see sticking around in the UI are other identifier and permalink.  Also the record that I imported (IUCAT: 3297348)  had duplicate english entries after bib import.

**Comment by jlhardes** [comment]
Is permalink being added onto so you end up with multiple permalinks and only one of them really works?

**Comment by cjcolvar** [comment]
No, I don't think permalink is ever brought in via bibimport.  Permalink is single valued as well.

**Comment by jlhardes** [comment]
OK, so permalink just isn't changed with a bib import. That's good - permalink is something generated by Avalon and shouldn't be overwritten by anything from a bibliographic record. Thanks!

**Comment by mcwhitaker** [comment]
@joncameron I am working on QA for this ticket now.

**Comment by mcwhitaker** [comment]
QA completed. Moving to done.
