### ISSUE TITLE
Failed to auto-switch between sections of different types

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1838]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Exploratory
Browser: Chrome(56.0.2924.87 (64-bit)), checked on Firefox(50.0.2) as well
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Player is not automatically switching sections of different types, i.e. audio and video sections. audio-to-audio and video-to-video switching is fine but no audio-to-video and video-to-audio.

### Expected behavior
player auto switches to proper player (audio or video) depending on format. This is for both playlist items and vanilla items. 

### Actual behavior

Player is not switching. 

### Steps to reproduce the behavior
1. Login to spruce system
2. Add an item with with a video section and an audio section.
3. Go to preview and play the video section
4. After the video is finished playing it doesn't switch to next audio section.

### Related work

Link to related tickets or prior related work here.

### Tasks
- [ ] Isolate and fix
- [ ] QA test to make it switching works in both directions and players look decent
- [ ]  Test to ensure switching works when user initiated or when automatically advanced

**Comment by Karthikeya212** [comment]
Similar issue is seen with playlist items as well

**Comment by joncameron** [comment]
Brian notes that this is probably the same bug as the playlist issue that Karthik mentioned.

**Comment by bkeese** [comment]
This is related to whether or not structural metadata is available on a section. Links are handled in the Sections display differently depending on the availability of structural metadata.  https://github.com/avalonmediasystem/avalon/blob/develop/app/views/media_objects/_sections.html.erb#L77

**Comment by Karthikeya212** [comment]
The player is switching correctly between sections of different types, but it is not playing them automatically after switching unlike the auto-play that is working between the sections of same type. Is this the expected behavior?

**Comment by joncameron** [comment]
@Karthikeya212  The expected behavior should be that the next section begins playing automatically, even if it's a different content type. Let's consider this one closed since you mentioned it's working, but create a new bug report for auto-play instead of auto-switch.
