### ISSUE TITLE
iiif player can consume audio and video at the same time

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1852]
## Description

Some works will be comprised of _both_ audio and video media. IIIF -av should be able to represent these works, and the avalon player should be able to consume the manifest and play the content. A single player should be represented on a page. 

## Done looks like

- the player can consume the manifest and play the media based on example manifest in #1851
- the player swaps based on audio _or_ video

## Tasks
- [ ] Create an example manifest which has both audio and video canvas elements in the canvases array
- [ ] #1946 Update hash handler to account for current canvas selection in URI.
- [ ] In UI, trigger destroy of current player and re-loading of new player based on user selection media type (whether audio or video canvas was selected)

**Comment by davidschober** [comment]
@joncameron can you add  a link to a mixed media example from pawpaw?

**Comment by adamjarling** [comment]
@joncameron @davidschober  Currently @little9 and I are working on two separate audio / video manifest structures, and seems to address this story, we choose one format as the current 'working JSON structure'.

When consuming a combined audio / video manifest for this story, and for a use case: 
* Will the player display two separate players (audio/video) on a page when reading a combined manifest?   
* Will the user select in the UI (through a menu/link/dropdown) which part of the manifest (audio or video or image say) the player will display?

Currently there are examples of manifests representing both audio and video.  And currently the Hyrax player can consume both manifests and play the media.  So maybe we just clarify how we should present this issue's use-case in the UI.

**Comment by davidschober** [comment]
There will only be one player at a time.

**Comment by adamjarling** [comment]
@davidschober @joncameron This may have been a duplicate ticket, and the work is finished.
