### ISSUE TITLE
Build iiif-av manifests with Manifest Gem

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1856]
### Description
The iiif_manifest gem is currently in projecthydra-labs:
https://github.com/projecthydra-labs/iiif_manifest

This is informed by #1854

### Done looks like
So we can generate IIIF representation 3.0 manifests for the endpoint(#1775).

### Tasks
- [ ] Create a branch within the IIIF Manifest gem for the 3.0 (av) spec
- [ ] Investigate what changes need to be made to add AV and make it 3.0 compliant.
- [ ] Make those changes.

**Comment by joncameron** [comment]
Does this need to be broken?

**Comment by joncameron** [comment]
I'd like to talk with devs about the tasks on this one before I feel it's ready for prime time.

**Comment by cjcolvar** [comment]
@joncameron We think this is tasked.  Ping us if you have any questions.

**Comment by cjcolvar** [comment]
@joncameron @davidschober @mcwhitaker Can we close this now?

**Comment by davidschober** [comment]
done with other work.
