### ISSUE TITLE
extract hyku's iiif manifest MVC into a plugin for hyrax.

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1857]
This is upstream community work. 

## Done looks like:

Hyrax has a IIIF manifest plugin to extend/ work with

## Tasks
- [ ] Connect with interested hyrax developers
- [ ] Review prior work by Thomas Scherz and others
- [ ] Extract Controller behavior from hyku
- [ ] Decide to build a plugin or PR directly to hyrax
- [ ] Build plugin (if necessary)
- [ ] Test with image and av manifests

**Comment by joncameron** [comment]
This already got done. Closing...
