### ISSUE TITLE
[EPIC] Incorporate current r look into IIIF Player

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1858]
## Description

With the move into Hyrax we have settled on an updated media element player consuming a IIIF manifest. We need to skin media element to have a similar look and feel as the current avalon 6.x player (with updates as necessary).  It should incorporate elements from the list Adam has created in #1860.

Core Features:

* Sharing
* Play/Pause
* highlighted sections
* marker pointers
* add to playlist and dialogue
* add to marker and dialogue  
* Accessibility features  ( @joncameron and I to add list )

## Done looks like
The IIIF driven player has a similar look and feel to the current 6.x player.

**Player Icons**
- [ ] #1843 #1848 - Quality selector
- [ ] #1879 - Track scrubbing
- [ ] #1880 - Create thumbnail
- [ ] #1881 - Add to playlist
- [ ] #1885 - Add marker to playlist view
- [x] Can play/pause (default mediaelement functionality)
- [x] Can toggle full screen mode (default mediaelement functionality)

**UI**
- [ ] #1886 - Share tabs
- [x] #1887 - Sections - List and link to ranges or content areas in the player
- [ ] #1888 - Sidebar metadata display

** Other **
- [ ] Review current accessibility features existing in the current player
- [ ]  Add accessibility features to list above

**Comment by adamjarling** [comment]
Blocked by #1860

**Comment by adamjarling** [comment]
@davidschober @joncameron @little9 Next steps on the player as of now (May 8, 2017) seem to be:
-  Decide whether we want the player to display only one player at a time (audio or video), so the section URI links work.
- Test pulling in previous Mediaelement plugins into the Hyrax player.

**Comment by mcwhitaker** [comment]
@davidschober @joncameron @adamjarling In Avalon r6 we show only one player at a time.  Are we considering the features of the current Avalon for this task or are we adding new features?

**Comment by davidschober** [comment]
No new features. Avalon will have a single player.

**Comment by joncameron** [comment]
Yes, the mediaelement player itself in the page should be able to switch between audio and video as needed—like on the playlist view when both types of media are present as playlist items, or on an object that may have both types of media as different sections.

**Comment by davidschober** [comment]
@adamjarling can you update this one? It's in needs refinement, but maybe it should be in "in progress" or ready since it's a master issue you're working on.

**Comment by davidschober** [comment]
Note @joncameron to get the accessibility team to review the IIIF player

**Comment by adamjarling** [comment]
@davidschober @joncameron Now that we're moving forward with MediaElement4, should we either alter this story to reflect that the IIIF standalone player should follow suit on the new ME4 implementation, or abandon this story and start a fresh story?

**Comment by joncameron** [comment]
@adamjarling I'm inclined at this point to create a fresh story for ME4 specifically since much of this was written targeting an earlier goal of the player but the checklist stuff is mostly still relevant. @davidschober What do you think?

**Comment by davidschober** [comment]
sounds good. Let's do that. Abandoning this issue.
