### ISSUE TITLE
ActiveFedora External File PR

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1859]
Continue to track and shepherd the ActiveFedora PR focused on external file support:
https://github.com/projecthydra/active_fedora/pull/1234

### Done Looks Like
Developers have support in ActiveFedora for storing references to external content for files.

### Tasks
- [ ] Review Fedora discussions on external-content particularly https://github.com/fcrepo/fcrepo-specification/pull/121
- [ ] Decide if external-content is still the right approach for Avalon streaming derivatives
- [ ] Rework ActiveFedora PR to reflect changes to fedora spec
- [ ] Respond to PR feedback

**Comment by davidschober** [comment]
@cjcolvar is this still relevant? It looks very stale?

**Comment by cjcolvar** [comment]
I closed that AF PR and I think we can close this issue.  I think our latest thinking is to store references to external files in a different way.
