### ISSUE TITLE
IIIF Media Player - File Quality UI Selector

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1878]
### Description
In the new Hyrax Mediaelement player, provide the audio/video quality selection functionality which currently exists in the Avalon 6.x player.

### Done Looks Like
- Video player has a quality selection icon
- Audio player has a quality selection icon
- Selecting video quality option loads the correct file
- Selecting audio quality option loads the correct file
- Audio/Video manifest file represents multiple file qualities

### Tasks
- [x] Add video player quality selection icon.
- [ ] Add audio player quality selection icon.
- [x] Load correct file when selecting video quality option.
- [ ] Load correct file when selecting audio quality option.
- [x] Represents multiple file qualities in manifest files.

**Comment by adamjarling** [comment]
Using this URL for testing:

https://raw.githubusercontent.com/avalonmediasystem/avarax-poc/feature-quality-selector/app/views/demo/iiifavaudio.html.erb

**Comment by adamjarling** [comment]
We can/probably should use MediaElement 4's default plugin for this functionality.

**Comment by davidschober** [comment]
@adamjarling should I abandon this? It seem like this has become redundant with your ME4

**Comment by adamjarling** [comment]
@davidschober @cjcolvar  Agree.  Jamie's file quality selector approach is still live in the IIIF POC player, however we'll need to make a decision on that integration when we pull the IIIF MEJS4 player into Avalon.   This depends upon whether we want to represent file qualities (and potentially any other audio/video property) in the URL hash. ie ` http://someurl.edu/canvas/1/quality/medium/type/audio/someKey/someValue` or not.   Does this follow any existing pattern in Avalon, or seem like it's a logical & maintainable approach for Avalon?

**Comment by cjcolvar** [comment]
@adamjarling I don't think Avalon uses URL hashes at all right now.  I also don't think that Avalon captures the quality in the URL.  Since Avalon 6.x has a limited amount of time left does it make sense to introduce it and change UX behavior?  I'd vote for trying to keep things as close to the MEJS2 player in terms of UI including URLs if possible.  If it is a considerable amount of work over the code you brought in from the IIIF POC player then I might be swayed.

**Comment by adamjarling** [comment]
@cjcolvar @davidschober @joncameron  I think I agree.  Unless anyone is really excited about using hash params, seems easiest to build from MEJS4's file quality plugin as a code base.   I think we could close this issue, then perhaps it warrants opening a new issue whose scope would be implementing MEJS's file quality plugin in the IIIF player?

But, eventually the work on Avalon's 6.x MEJS4 player should be at a point where it's easiest to extend it's functionality with the IIIF player's parsing/rendering capabilities.  And instead of doing things twice, we just focus on current MEJS4 player to get it working with the application, then bring in the IIIF functionality to it.  This make sense as a broad path forward?
