### ISSUE TITLE
Media element 4 - Track Scrubbing

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1879]
### Description
Re-create track scrubbing (lil' scrub) functionality from Avalon 6.x player into MEJS4 player.  After a discussion with @joncameron we're going to limit the scope of this ticket to just the mediaobject view, and not the playlist page.

### Done Looks Like
lil' scrub is implemented in  Mediaelement 4, along with the highlighting on the main scrub bar (#2184).

### Tasks
- [x] Add scrubber icon (magnifying glass) to player
- [ ] Make scrubber icon toggle lil' scrub.
- [ ] Add track highlighted on main scrubber (#2184)
- [ ] Verify track scrubbing functionality works as expected

**Comment by davidschober** [comment]
@adamjarling for this one you're looking at the little zoom scrubber, correct?

**Comment by adamjarling** [comment]
@davidschober Yea I was going to try using the scrubber plugin, see how to wire that into the Hyrax app.

**Comment by adamjarling** [comment]
Pointing this currently at a 5, as some of the plugin documentation to bring into a Rails application is somewhat limited.   First approach is to re-use previously created mediaelement plugin.  If that doesn't work with current version of mediaelement, will need to create from scratch which will be significantly more work.

**Comment by davidschober** [comment]
@adamjarling is this issue still relevant?

**Comment by adamjarling** [comment]
@davidschober Yes, it's still relevant as an overarching work item, but the description, Done Looks Like, and Tasks, may need to be revised somewhat.  I do that before starting on this story.

**Comment by adamjarling** [comment]
I think it makes sense to complete #2184 first, before working on this ticket.
