### ISSUE TITLE
Media element 4 - Add To Playlist feature

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1881]
### Description
Re-create add to playlist functionality from Avalon 6.x player into Hyrax Mediaelement player.

### Done Looks Like
Add to Playlist functionality works the same in the Hyrax environment as it does in current Avalon environment.

### Tasks
- [ ] Add to playlist icon added to both video and audio players
- [ ] Create the add to playlist dropdown UI markup
- [ ] Toggling icon brings up the add to playlist dropdown UI (see screen shot)
- [ ] Submitting the add to playlist dropdown UI, posts data successfully to the correct endpoint
- [ ] Add to playlist dropdown UI behaves appropriately (closes?  stays open?) when playlist selection is submitted
- [ ] Kick off new issues as necessary (for bugs and backend work)

<img width="1150" alt="avalon-player-add-to-playlist" src="https://cloud.githubusercontent.com/assets/3020266/25710172/175dee5e-30b1-11e7-8c8e-d13c7912cab3.png">

Depends on #1811 and #1807
