### ISSUE TITLE
Media element 4 - Add Marker

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1885]
### Description
Add markers to videos in 'playlist' view.

### Done Looks Like
- Investigate current implementation of adding markers to a video (and audio?) and understand the ux/flow.
- Re-create add marker functionality from 6.x Avalon player, to Media  Element 4 player, building on the markers Mediaelement 4 plugin.

### Tasks
- [ ] Investigate current method and/or plugin for adding/editing markers
- [x] Pull in markers plugin
- [ ] Wire up add marker functionality to proper endpoints
