### ISSUE TITLE
Enable Share feature in Hyrax - Share Feature (front end)

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1886]
### Description
Hyrax mediaelement player should have same 'Share' functionality as Avalon 6.x player.  Note this is only to stub out the front end work. The video and audio UI share tabs will include:

- Share this resource
- Embed

Additionally, if LTI is configured, the share UI will have the following tab:
- LTI URL

### Done Looks Like
- The correct share code is generated and available to user.
- The UI markup / component dropdown, toggle behavior: possibly re-factor the markup to work with new MediaElement.

### Tasks
- [ ] Share button/icon added to UI
- [ ] Share button toggles tabbed UI
- [ ] Tabbed UI form inputs populate with the correct URIs/data

![avalon-player-share](https://cloud.githubusercontent.com/assets/3020266/25752192/24715be0-317d-11e7-906a-6881ce5df490.png)

**Comment by adamjarling** [comment]
Pointing at a 3, assuming the mediaelement plugin will work with our Hyrax mediaelement player.

**Comment by davidschober** [comment]
Note, this should also work with LTI share/embed

**Comment by davidschober** [comment]
@adamjarling this is outside of the context of the player itself. We will relabel R7 and move down the line.

**Comment by adamjarling** [comment]
@davidschober Ok, sounds good.

**Comment by joncameron** [comment]
UV provides a sharing modal. One approach being: put it into the player itself. We may not need to have LTI specific links anymore, which would eliminate that from consideration about displaying of share content.
