### ISSUE TITLE
Update Pawpaw Comment Email Address

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1892]
### Description
As a team member, I want the comments form on pawpaw to send email to avalon@dlib.indiana.edu instead of vovcomment@dlib.indiana.edu so the latter can be retired. This will allow us to not have to manage multiple redundant email addresses.

### Done Looks Like
avalon.yml for R6 on pawpaw.dlib.indiana.edu  has comments sent to avalon@dlib.indiana.edu. Looks something like this after the change:

>email:
>    comments: avalon@dlib.indiana.edu
    notification: avalon-core-l@list.indiana.edu
    support: avalon-core-l@list.indiana.edu
    mailer:
      smtp:
        address: mail-relay.iu.edu
        port: 587
        enable_starttls_auto: false

### Tasks
- [x] Make it so
- [x] Replace sendmail with postfix for consistency
- [x] Test email sent and verified
