### ISSUE TITLE
Write docs for multi-threaded migration tool

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1916]
### Description
As a system administrator I want documentation on how to safely run migration tasks with multiple threads.

### Done Looks Like
Documentation is written for the multi-threaded migration. Ticket for creation of that: #927. 

### Tasks
- [x] create documentation for users on how to tune so they don't blow up machine by spawning Fedora and SOLR threads.
- [x] Explain parallel_processes option
- [x] Add section for known issues / common errors and workarounds

### Reference Issues
#2036 Documentation for Migration and Migration Report

**Comment by davidschober** [comment]
Make sure we have a header for "known issues or Gotchas" to capture oddities, ldc conflicts, etc.

**Comment by cjcolvar** [comment]
https://wiki.dlib.indiana.edu/display/VarVideo/Migration+Tool
