### ISSUE TITLE
Move player to work display page and allow arbitrary IIIF manifests (POC)

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1930]
## Description

Currently our IIIF POC player is hijacking an "about" page in Hyrax. In order to offer more flexibility while the team creates a 'ready for prime time' video content work (or generic work) that can create a IIIF manifest, we would like to create a stripped "POC" work type that has a metadata field pointing to a static IIIF Manifest. The view would use the manifest field to generate a player. This will allow us to create and test any number of works showing a variety of content driven by an IIIF player (e.g. audio, video, complex audio, audio and video mixed).

## Done looks like

- a POC work-type is create with an extra field (or some other method to get an arbitrary iiif manifest.
- We can create an arbitrary number of IIIF manifests 
- we can test different manifest types 
- An end user can put in an arbitrary line to a IIIF  manifest
- Player displays on Work page.

## Tasks

- [ ] New Work Type generated in avarax-poc
- [ ]  Add metadata field for url of iiif manifest to model
- [ ]  Add metadata field for url of iiif manifest to form
- [ ] Index metadata field for url of iiif manifest
- [ ] Add metadata field for url of iiif manifest to presenter
- [ ] Add metadata field for url of iiif manifest to show view
- [ ] Initialize iiif player on show view using the stored iiif manifest

**Comment by joncameron** [comment]
This will be a throwaway thing meant for demos rather than a path we'll take.

**Comment by davidschober** [comment]
Note, I'm not married to creating a new work type. If there's another way to handle this let's do it. The goal is the same, quickly test out different types of manifests, and get to working on the front end.

**Comment by davidschober** [comment]
@cjcolvar and @adamjarling I think this went a different direction. We built out the POC player and have broken out "avalon in Hyrax" issues correct? I'm closing let me know if you want to reopen.
