### ISSUE TITLE
Structural Metadata Editor - UI Discussion

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1931]
## Description

We need to make a decision about how structural metadata will be edited within a hyrax-driven environment. Currently our structural metadata editor is a quick and dirty xml editor. The schema currently: https://github.com/avalonmediasystem/avalon/blob/dd9ea47de0fb4cc3bc2503b0b414e98fd2ea48ae/public/avalon_structure.xsd

An ideal solution would be to have editable fields associated parent and children which have a label and time extent so that an end user  can add a parent and the children and never have to touch the xml.

## Done looks like 

- Path forward is determined
- sketches are made of interface, ideally using a "hyrax-y" way of doing it
- if we punt on a visual, point and click editor, a clear path to that end is documented
- A review of hyrax design patterns if necessary
- break out technical stories as necessary.

## Tasks

- [ ] Review current graphical interface in Avalon
- [ ] Review current Hyrax interface and consider what a Hyrax style editor would look like
- [ ] developers review Hyrax UI patterns
- [ ] wireframes generated

**Comment by bkeese** [comment]
Our current editor does have a graphical interface option that sounds like what is described here. It's a bit clunky though and might only serve as an example of what we want and don't want. To see it, just click the "Graphical" button within the editor.

**Comment by carrickr** [comment]
I did task this out, but honestly it seems like we could split this into multiple tickets.  This could remain as the parent perhaps.

- One for a group of people to review the current editor and current Hyrax fielded data editors (that might inform the design for ours)
- one for developers to review UI design patterns
- one for designers to generate wireframes

This also feels a bit small at 3 considering the number of people impacted by the design.

**Comment by jwd** [comment]
I strongly believe that what we ultimately need here is an interactive playlist editor that works with the player so that time points can be pulled in from current scrubber location, allowing the user to scrub around to find timepoints from which to construct structural metadata elements.

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#103
