### ISSUE TITLE
Determine how to store structural metadata

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1936]
## Description

In the move to hyrax, we have the opportunity to revisit how we store structural metadata. Currently it's stored as an attached xml file . Do we continue down this path or find a new one. 

Should we back up to work level, interfile, etc. 

This is related to #1360

this breaks out #1931

## Done looks like

- a decision is made about how to store structural metadata
- OR other issues are broken out to further knowledge spike
- Issues are broken out for technical work necessary.

### Tasks
- [x] Background information and possibilities collected
- [x] Meeting to discuss possibilities
- [x] Plan selected and documented
- [x] New stories written for implementing plan

**Comment by davidschober** [comment]
We are going to store it as xml, similar to how we were before. Done.
