### ISSUE TITLE
Create stand-alone app showcasing IIIF player

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1937]
## Description

Based on work in #1929, create app (single web page) that showcases our parsing of a manifest.

It should have:
- A player
- Clickable structure
- Basic controls
- A field to input an arbitrary manifest URL

## Done looks like
- A standalone player app can be hosted anywhere (e.g. github pages) for ease of demoing
- QA on page verifying player works, clickable structure works, and input file for manifest works.

### Tasks
- [x] Build app structure, with webpack/NPM
- [x] Create a distribution 'dist' output directory.

The tasks below will be done for #1956
- [ ]  Create input field for external manifest URL. broken into #1956 
- [ ] Wire up app using external manifest URL to feed the player
- [ ] Display graceful error message when external manifest URL is not properly formatted, and/or player doesn't parse manifest correctly.

**Comment by davidschober** [comment]
This looks great. I noticed it's not playing in Safari. If that's too tricky, let's put a note at the top for now.

**Comment by davidschober** [comment]
@adamjarling and @little9 do you want to break out the input field story? I think this issue may have been too big.

**Comment by little9** [comment]
@davidschober was it in mobile Safari or the desktop version?

**Comment by davidschober** [comment]
Sorry, Desktop.

**Comment by little9** [comment]
@davidschober hmm it looks like Safari doesn't support cross origin video/audio content. 

https://bugs.webkit.org/show_bug.cgi?id=135379

**Comment by davidschober** [comment]
k. Let’s put a note at the top of the page?

**Comment by adamjarling** [comment]
I can add this in tomorrow.

**Comment by adamjarling** [comment]
Just poking around at this a bit, and if you click on an area within the track timeline itself, it will play audio/video in Safari.  Maybe it's how Safari handles hash change events?

**Comment by little9** [comment]
You're right, it's the hash change event! Here's a Stack Overflow page with about a million workarounds, we'll just need to pick one:

https://stackoverflow.com/questions/3090478/jquery-hashchange-event

**Comment by adamjarling** [comment]
I've been looking at this, and looks like Safari is picking up the onhashchange event ok.  It's something in Safari not executing the `mediaPlayer.play()` line?
