### ISSUE TITLE
In Chrome, the Avalon Player does not ask to run

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1948]
In Chrome (known to occur in 58.0.3029.110), when Chrome is set so that Flash needs to ask before running, Avalon does not ask to run flash.  Rather Chrome just fails to run.  For additional info see the work around documentation on it:  
https://github.com/avalonmediasystem/avalon/wiki/Streaming-Media-in-Chrome-(Avalon-4,-5,-and-6)

As noted by @bmquinn, there is web console chatter on this
```
mediaelement-and-player-d6cb9817c4e212588697a3fdeaa43314.js:2968 Uncaught (in promise) DOMException: The element has no supported sources.
(anonymous) @ mediaelement-and-player-d6cb9817c4e212588697a3fdeaa43314.js:2968
dispatch @ application-f1c496a5138d9c24796f91db8f26bd4c.js:4689
elemData.handle @ application-f1c496a5138d9c24796f91db8f26bd4c.js:4357
```

*Important Note* Currently it seems once you whitelist in Chrome there is no going back.  Even if you delete the whitelist entry and restart Chrome, somehow the exception seems to persist.  So when testing a fix for this, be sure to use a machine that never whitelisted, a VM, etc.

## Done Looks Like

Avalon asks to run its flash through Chrome rather than requiring a manual white list.

http://get.adobe.com/flashplayer/about/ is a good exemplar of desired behavior, chrome will show the plugin blocked error there.

## Tasks
- [ ] POs decide how far back to patch this (confirmed to occur in 4, 5, and 6)
- [ ] Player is fixed in desired versions
- [ ] New releases of all versions cut
- [ ] [Wiki Documentation](https://github.com/avalonmediasystem/avalon/wiki/Streaming-Media-in-Chrome-(Avalon-4,-5,-and-6)) is updated to reflect that the problem can be resolved by installing a new version of Avalon rather than requiring users to white list and/or that it is a known and won't fix problem for older versions of Avalon

**Comment by davidschober** [comment]
@joncameron we may have to do a quick patch back to 4 as we're still in production for a couple of weeks. ) If this becomes too cumbersome, I'm OK with patching to 5.

**Comment by carrickr** [comment]
As a note to POs, if you go to http://get.adobe.com/flashplayer/about/ you should get a Chrome message about blocking flash.  When you click on that message and then select `Manage Exceptions`, you're taken to the exceptions page with zero context.  So it's not exactly awesome for users and we should document that.

**Comment by davidschober** [comment]
We decided to abandon this. I believe. We will update NU's warning as a stopgap for 4.0

**Comment by davidschober** [comment]
OK. I'm a bit confused here. I thought in slack, we said it was showing an error page in 6.x. When I hit mallorn, I see the same behavior as Avalon 4.x(nu prod). (poster drops and no end time is shown). I think this might take some investigation.

**Comment by mcwhitaker** [comment]
@davidschober You have to make sure you use an item for which the content is available. Several items in mallorn don't.

I use these: https://mallorn.dlib.indiana.edu/?f%5Bcollection_ssim%5D%5B%5D=Yonder+Mountain+String+Band&q=&search_field=all_fields

**Comment by davidschober** [comment]
I’m getting 00:00—>00:00 without an error . I’m running the chrome Version 58.0.3029.110 (64-bit)

https://mallorn.dlib.indiana.edu/media_objects/ns064605c <https://mallorn.dlib.indiana.edu/media_objects/ns064605c>

**Comment by mcwhitaker** [comment]
@davidschober In that case, I would say you have confirmed the issue. I can't reproduce it because I already have our domain white-listed. Even when I set chrome to block flash, I get to play the items.

**Comment by davidschober** [comment]
That’s what I’m thinking. I thought I saw someone’s screenshot from yesterday that showed the proper error message. (I’ll admit I was reading fast). K. We need to look at this in the sprint.

**Comment by cwant** [comment]
Just wondering ... when the label says 'abandoned', does that mean nobody will work on it? (We've been hit with this one too on our fork of Avalon 5.1.5.)

**Comment by cjcolvar** [comment]
@cwant 
It has been abandoned.  I don't think we found any good way to handle this without requiring action by the user.  Personally I notice this on many sites that use flash and have developed a habit of switching flash from ask to allow on each site I see it happen.  This should be equivalent to what @carrickr documented [on the wiki](https://github.com/avalonmediasystem/avalon/wiki/Streaming-Media-in-Chrome-(Avalon-4,-5,-and-6)) and less expansive than allowing flash for all sites.  Here is [another page](https://wiki.dlib.indiana.edu/display/MCO/Enabling+Flash+Player+in+Google+Chrome) documenting this process for IU's production avalon.  If you find a better solution, we'd love to see it!

@avalonmediasystem/product-owners @mcwhitaker 
Does this sound accurate to where we ended with this issue?

**Comment by mcwhitaker** [comment]
Yes. We still aim at not requiring flash as soon as it is feasible.

**Comment by davidschober** [comment]
Yes, in addition, we are driving forward with our work on MediaElement 4. Some of the odd behavior (dropping a player without time) seemed connected to our fork of MediaElement 2.

**Comment by cwant** [comment]
Thanks all. I don't think Google treated their users very well with this one. If I discover anything useful as I investigate further, I'll be sure to pass it along.
