### ISSUE TITLE
New media objects should have a recordIdentifier for its Fedora4 uri

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1954]
### Description
MediaObjects in Avalon 5 have a MODS recordIdentifier of their Fedora3 pid and source "Fedora".  When migrated the MODS gets an additional recordIdentifier containing the Fedora4 uri and source "Fedora4".

## Observed behavior
New media objects in Avalon 6 end up with MODS containing an empy recordIdentifier with source "Fedora".

## Expected behavior
New media objects in Avalon 6 get a recordIdentifier in MODS containing their Fedora4 uris with source "Fedora4".

### Done Looks Like
All Media Objects in an Avalon 6.1 system have a recordIdentifier element in their descMetadata MODS document containing their Fedora4 uris and with source "Fedora4"

### Tasks
- [x] Fix MODS OM template so source is "Fedora4"
- [x] Add the Fedora 4 uris of the media objects to recordIdentifier
- [x] Write a migration to fix all existing MODS documents
- [x] Update any documentation to reflect change of source to "Fedora4"

**Comment by davidschober** [comment]
This looks good.

**Comment by davidschober** [comment]
@cjcolvar can you throw some points on it?

**Comment by cjcolvar** [comment]
I'm verifying this on spruce.

**Comment by cjcolvar** [comment]
Fixed on spruce but still need to write migration and update documentation.

**Comment by cjcolvar** [comment]
Added a post-upgrade step to upgrade documentation: https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.0+to+Avalon+6.1
