### ISSUE TITLE
Release 6.1

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1969]
### Description
Releasing 6.1 to the world after code work in #2031 is competed.

### Tasks
- [x] Write a draft of release notes on Github
- [x] Publish release on Github https://github.com/avalonmediasystem/avalon/releases
- [x] Update wiki with release notes as needed
- [x] Publish blog post announcing the release
- [x] Put announcement on Twitter and Facebook
- [x] Send out email to Samvera community mailing list
- [x] Publicize in appropriate Slack channels
