### ISSUE TITLE
ME4js: audio player is not auto switching between CD's

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1974]
Server: https://avalonmediasystem.github.io/avalon-poc-standalone/dist/
Testing: Smoke
Browser: Chrome(58.0.3029.110 (64-bit))
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Audio player is not auto switching from one CD to the next. User has to clicking on the CD link manually to start playing it.

### Steps to reproduce the behavior
1. Open the above mentioned server location.
2. Go to the Audio player and start playing.
3. Go to the end of CD1, and wait for it to end.
4. After ending CD1 it gives option to reload CD1 but doesn't start playing CD2
![no-switch_cd](https://cloud.githubusercontent.com/assets/25850972/26651811/e28179be-461b-11e7-9057-fd82a2dba3dd.PNG)

### Done Looks Like
- Sections play continuously.  
- Different canvas source elements represented in the manifest structure, will automatically play the next canvas media element.

### Tasks
- [ ] Set up callback/listener functionality for when end of a media clip is reached
- [ ] Within above callback function, determine where in the overall manifest sections structure the media file is located (in the middle someplace, at the end, etc.)
- [ ] If there are navigable next sections, make Mediaelement instance play the next source file.

### Related work

Link to related tickets or prior related work here.

**Comment by davidschober** [comment]
I think we can tackle this one when we add auto-play features, etc. @joncameron

**Comment by joncameron** [comment]
Yes, this is a refinement that can take a backseat for at least a little while.

**Comment by adamjarling** [comment]
Doesn't look like there is a Mediaelement plugin for this (https://github.com/mediaelement/mediaelement-plugins) at the moment, so we'll have to create a custom solution.

**Comment by davidschober** [comment]
@adamjarling  this one that we need to get done with for ME4js? Maybe we should rewrite this toward ME4js @joncameron

**Comment by adamjarling** [comment]
@davidschober I need to add this functionality into the MEJS4 js wrapper, auto-playing the next item when there's a list of items.   This is POC and the MEJS4 Avalon, but the functionality will be built into what I'm working on now, then POC player can inherit the functionality.
