### ISSUE TITLE
Standalone Player: video is beginning from start of the section when quality is changed

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1976]
Server: https://avalonmediasystem.github.io/avalon-poc-standalone/dist/
Testing: Smoke
Browser: Chrome(58.0.3029.110 (64-bit))
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Video is beginning from start of the section when quality is changed.

### Expected behavior
The video should be continuing from its current position with updated quality

### Steps to reproduce the behavior
1. Open the above mentioned server location.
2. Go to the Video player and start playing.
3. At any point click on the "quality" button and change the quality, the video starts again from the start of its current section.

### Related work
Note: This issue is present in mediaelement. Current Avalon mediaelement forked code has a fix that requires flash. When we move away from flash, another solution will be needed

### Tasks
- [ ] Investigate default Mediaelement 4 functionality when switching quality levels.
- [ ] Next steps depend on outcome of first task step.  
- [ ] Research preferred way to handle file quality selection changes in Mediaelement.js.  Are there existing plugins, or solutions to keep playback continous?
- [ ] Work towards desired outcome (create a new task specific to what we know at this point.

**Comment by davidschober** [comment]
@adamjarling can you dig into how this works on the current system?

**Comment by davidschober** [comment]
I think this should be pushed to a feature request for the IIIF player rather than a bug. The on -the fly switching was a bit out scope for this phase.
