### ISSUE TITLE
Standalone Media Player - Combine Audio and Video pages into one player/structure/UI

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1995]
### Description 
Currently there are 2 pages in standalone player app, Audio and Video.  These should be combined into one single UI, which consumes a manifest file which maybe have video, audio, or both.  The player should respond to mixed media type manifests.

### Done Looks Like
- Audio and Video pages consolidated into one page.
- The UI displays a structure which represents and updated manifest file, which may contain audio, video, or mixed canvases
- Mixed media manifest file created/supplied to standalone player
- The UI displays a player which responds to the media type of it's canvas (audio or video player).

### Tasks
- [ ] Create a new single player page
- [ ] Consolidate classes to more generic functionality (break out into Feature Issue)
- [ ] Update parsing logic (same feature issue as above) to be more generic
- [ ] Determine how to handle quality selector

**Comment by adamjarling** [comment]
Duplicated by #2132

**Comment by davidschober** [comment]
closing as duped
