### ISSUE TITLE
Standalone Media Player - Update webpack configuration dev environment

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1996]
### Description
Update the webpack bundling to support a better development environment.

### Done Looks Like
- Move *.html files to /app directory for development.
- Have dev environment reference local /app es6 JS files instead of bundled webpack output JS files in /dist.

### Tasks
- [x] Update webpack dev to use webpack server
- [x] Update webpack dev to display live updates in browser via a watcher
- [x] Modularize webpack config files
