### ISSUE TITLE
Final 6.1 Code Merge and Code Freeze

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2031]
### Description
Code merges, update and cleanup for the public release of 6.1.

### Tasks

- [x] Update version in code
- [x] Update license headers in files
- [x] Tag dependency repos
- [x] Update gemfile to point to those tags
- [x] Latest 6.1rc merged into master
- [ ] Create tag for v6.1.0

**Comment by cjcolvar** [comment]
The last task will be completed with #1969.
