### ISSUE TITLE
Migration Report Details Page Tweaks

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2043]
### Description
Based upon feedback from @jlhardes, the following improvements should be made to the migration report detail page.

### Done Looks Like
Migration Report Details pages have been improved to deal with identified issues.
 
### Tasks
- [x] expand N/A to Not applicable
- [x] Give a different details page for non-Fedora items (e.g. markers, clips, playlists, bookmarks)
- [ ] in documentation explain what isn’t shown for fedora 4 objects like webACLs and list_source, master_files
- [ ] in documentation explain database objects vs. fedora objects

**Comment by lealeelu** [comment]
In my pull request I made the requested tweaks and a bit more. For the DB objects, I just removed the fedora sections since it doesn't apply. Chris mentioned it would be good to have not just the row number of those db objects in the details page title, but the actual record it's migrating from in fedora3. I think that would be useful but I can't test that on my dev environment. I'm going to have to punt that to a new issue if we want that.

**Comment by lealeelu** [comment]
As for the documentation, I made [this page](https://wiki.dlib.indiana.edu/display/VarVideo/Migration+Report+and+Results) and linked it [here](https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+5.1.6+to+Avalon+6.0).

**Comment by lealeelu** [comment]
Can someone read through my documentation to see if I need to add anything?

**Comment by bkeese** [comment]
Looks good to me. (I made a couple of edits.)

**Comment by cjcolvar** [comment]
Looking good.
@jlhardes how does this look to you?

**Comment by jlhardes** [comment]
I added a sentence near the end about access control and list_source objects not being viewable from the MediaObject migration report. I think that covers everything in the Tasks!
