### ISSUE TITLE
Speed up MediaObject destroy

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2047]
### Description
MediaObject currently takes too long to delete, especially when there are many sections, due to all the unnecessary updates/saves. Related issue #1965 and #1989

### Tasks:
- [ ] Reduce number of ActiveFedora callbacks
- [ ] Compare deletion time before and after, report result
- [ ] Make sure related MasterFiles and Derivatives are really deleted
- [ ] MediaObject should be inaccessible or show some message about being deleted (may split to another story)

**Comment by cjcolvar** [comment]
I just saw this in hyrax which might help a little.   Destroy list_source THEN master files.
```
        def cleanup_file_sets(curation_concern)
          # Destroy the list source first.  This prevents each file_set from attemping to
          # remove itself individually from the work. If hundreds of files are attached,
          # this would take too long.

          # Get list of member file_sets from Solr
          fs = curation_concern.file_sets
          curation_concern.list_source.destroy
          # Remove Work from Solr after it was removed from Fedora so that the
          # in_objects lookup does not break when FileSets are destroyed.
          ActiveFedora::SolrService.delete(curation_concern.id)
          fs.each(&:destroy)
        end
```
