### ISSUE TITLE
Standalone Player - Restructure parsing logic

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2058]
### Description
The standalone player parsing functionality should not hardcode target array elements in a manifest structure. 

### Done Looks Like
- No hardcoded array element references in parsing logic.
- Logic determines what type of player should be rendered from the 'content' array.
- Logic determines how many source files are present in manifest 'canvases' array (if it exists).
- Currently playing canvas is tracked in logic.
- UI structure links display correctly and link to the right media file and display the right type of player (audio or video player).

### Tasks
- [x] Remove hardcoded array element references in parsing logic.
- [x] Determine what type of player should be rendered from the 'content' array.
- [ ] Determine how many source files are present in manifest 'canvases' array (if it exists).
- [ ] Track the current player and current canvas (if multiple) in logic.
- [ ] Generate UI structure links which when clicked, accurately reflect manifest structure, link to the right file, and create an instance of the right player.
