### ISSUE TITLE
Failure to create ActiveEncode job returns unrelated job's metadata

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2060]
When ActiveEncode fails to create a transcoding job avalon gets updated with the workflow_id and thus metadata for an unrelated transcoding job.  It is not random and the metadata returned is always for the same transcoding job.  This is probably specific to the Matterhorn adapter.

## Done Looks Like
Error is presented to the user (instead of bad metadata) when transcoding job fails to start due to a failed create.

## Tasks
- [x] Create issue in ActiveEncode
- [x] Fix issue in ActiveEncode (optional?)
- [x] Handle exception or nil ActiveEncode::Base.id in Avalon

**Comment by cjcolvar** [comment]
Created PR https://github.com/samvera-labs/active_encode/pull/9

**Comment by Karthikeya212** [comment]
Issue is still seen in the below items, currently ongoing ingest please take a look.
https://mallorn.dlib.indiana.edu/media_objects/kh04dp71b
https://mallorn.dlib.indiana.edu/media_objects/zs25x846c

**Comment by cjcolvar** [comment]
Odd I'm not sure why that is happening other than if mallorn didn't get its queue server restarted when this code was deployed.  Or the bug is still present somehow.
