### ISSUE TITLE
Failed to auto-play the section after auto-switching to a section of different type

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2095]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Exploratory
Browser: Chrome(56.0.2924.87 (64-bit)), checked on Firefox(50.0.2) as well
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Failed to auto-play the section after auto-switching to a section of different type

### Expected behavior
If a section is playing and the next section is of a different type, the player will move to the next section and begin playing it automatically.

### Actual behavior
When media is playing and reaches the end, the player switches to the next section but does not keep playing if it is of a different type than the previous section.

### Steps to reproduce the behavior
1. Login to spruce system.
2. Browse for an item that has a mixture of different sections, and play the item.
3. The player will switch to the next section automatically, but it doesn't play the section if it is of a different type (i.e. video to audio or audio to video)

### Tasks
- [ ] Set up multi media section links.
- [ ] Observe current behavior in MediaElement 4 given the scenario above, and also see what happens when the same player type (video) follows a previously ended section.
- [ ] Write handlers in the new MediaElement 4 JS to handle end of player event.
- [ ] Construct a method to determine current place in structures list, and create a collection of all structures for which to interact with.

**Comment by davidschober** [comment]
Tabled until we implement media element 4.

**Comment by adamjarling** [comment]
Related to #1974 for description of the work in Mediaelement 4.

**Comment by adamjarling** [comment]
This functionality should be built into the MediaElement 4 JavaScript work.

**Comment by joncameron** [comment]
Closing as per Adam's comment. We'll create a new issue if needed post-MEJS4.
