### ISSUE TITLE
ME4 Media Player - Review and Implement Accessibility Features

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2130]
### Description
Test current accessibility of MediaElement4 player, and the structured sections links.

### Done Looks Like
- Current IIIF Player's accessibility features have been reviewed and beginning state documented.
- List of necessary accessibility improvements are detailed and new stories are created.

### Tasks
- [ ] Review and document current accessibility state of player and structured sections links.
- [ ] Create a list of improvements/enhancements
- [ ] Create stories from list of improvements/enhancements.

**Comment by cjcolvar** [comment]
Will need to handle being able to navigate into and out of the player via keyboard.  Quick testing on spruce shows that tabbing into the player from the beginning of the page works for end-users but shift-tabbing into the player from below it doesn't work.  For a user with edit privileges either way doesn't work.  I only tested on the item view page and not the playlist or embedded players.

**Comment by bkeese** [comment]
Tabbing into and out of the player was handled here: https://github.com/avalonmediasystem/avalon/blob/develop/app/assets/javascripts/keyboard_access.js

**Comment by phuongdh** [comment]
Tabbing and outlining buttons have been done. Is there a list of things left?

**Comment by adamjarling** [comment]
@phuongdh  Here's the document we just chatted about to reference:  https://wiki.dlib.indiana.edu/display/VarVideo/Accessibility

**Comment by cjcolvar** [comment]
Escape button to close thumbnail grabbing model is a problem in 6.2 so I suggest we skip it for 6.3.

**Comment by cjcolvar** [comment]
What is left to do here?  Are we done?

**Comment by davidschober** [comment]
@phuongdh can you give a thumbs up if we're done. I'll create a new issue for closing the thumbnail grabbing model via escape.

**Comment by phuongdh** [comment]
I think we're done.
