### ISSUE TITLE
Make Media Element 4 play a file within Avalon

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2134]
### Description
Get a piece of media running in mediaelement 4 within Avalon.

### Done Looks Like
- Pull mediaelement javascript into Avalon
 - Decide how the javascript/mediaelement assets will be pulled in—possibly something future compatible with webpack/Rails 5.1
- Media plays in the mediaelement 4 player within an Avalon 6 context on a developer machine on nginx.

Testing can be done on Flourine since it's already running nginx. Testing tasks are broken out separately.

### Tasks
- [x] Include mediaelement in the application in a preferred way, either through a mediaelement gem, or directly in /assets pipeline.
- [x] Create an instance of a player given an Avalon media file.
- [ ] Test the player works locally as well as on a staging environment.

**Comment by adamjarling** [comment]
For now, I'm putting the latest Mediaelement 4 files (.js, .css, .svg) into the Rails vendor assets pipeline.   Once we upgrade to Rails 5, we should use webpack, and pull in mediaelement through yarn at that point I'm guessing.

**Comment by joncameron** [comment]
This will be left open into Sprint 132 as per discussion in #2140.
