### ISSUE TITLE
Use Mediaelement 4 To Navigate Via Structure

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2135]
### Description
Clicking on section links will destroy a player and create a new player within the browser, with no page reload.

### Tasks
- [x] Display section links in MediaElement 4 player
- [x] Block default event behavior
- [x] Handle click events on section links

**Comment by adamjarling** [comment]
@mcwhitaker @davidschober @joncameron  I was able to complete this ticket as well, even though we originally pulled it out of the sprint.   I'll let you decide how to handle for metrics, whether we pull back in, re-adjust the numbers, or wait until next sprint and get a 5 point freebie.

**Comment by mcwhitaker** [comment]
@adamjarling For metrics, and if I understand things correctly after being gone for 2 weeks, I think the best is to pull it back into the sprint.

**Comment by adamjarling** [comment]
@mcwhitaker Ok, will do.

**Comment by adamjarling** [comment]
For a review, I could do a Blue Jeans quick meeting and show the current state of the MediaElement4 integration before end of day today?

**Comment by davidschober** [comment]
I’d love to see it. How about 2:30?

**Comment by adamjarling** [comment]
Sounds good.  https://bluejeans.com/7890815372

**Comment by davidschober** [comment]
We will be kicking off a new issue to navigate via structural metadata.
