### ISSUE TITLE
Update Pawpaw to 6.1

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2142]
### Description
Pawpaw, the Avalon demo server, needs to be updated to showcase the latest release.

### Done Looks Like
Pawpaw is running on Avalon 6.1.

### Tasks
- [x] Deploy Avalon 6.1
- [x] Upgrade to using database-backed Noid ID Minter
- [x] Restart/kick tires on Avalon services as needed
- [x] Test that a Manager-level user can successfully create a media object and that uploaded media is transcoded properly
