### ISSUE TITLE
Try Fedora 4.7.4

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2154]
### Description
So that I can see if it breaks our stuff. Also, so that we can report back to the Fedora folks about whether it breaks our stuff. 

### Tasks
- [x] Create Docker image
- [x] Try locally
- [x] Put it on Mallorn and have humans run through regression test script
- [ ] put together a load test (if possible)
- [ ] Report back to the Fedora folks

**Comment by cjcolvar** [comment]
We might want to try regression and performance testing with the parallel graph generation turned on:
```
Add support for leveraging parallelization in multiprocessor environments using -Dfcrepo.streaming.parallel=true.  Increase the "cacheSize" in the repository.json to whatever value your memory will allow to maximize the performance gains.
```

**Comment by davidschober** [comment]
@phuongdh did I hear you say you were working on this as part of Production?

**Comment by phuongdh** [comment]
@davidschober we were trying Andrew Woods custom build of 4.7.4 to see if it resolves our reindex timeout issue at IU.

**Comment by davidschober** [comment]
@phuongdh and @mcwhitaker it sounds like we should move this to in progress unless I'm misunderstanding (it's been a long week, totally possible).

**Comment by mcwhitaker** [comment]
@davidschober My understanding is that this ticket is to try the official fedora 4.7.4 with Avalon r6.

What we are doing now is a separate thing: @phuongdh is trying a non-official 4.7.4 version of fedora as part of our effort to resolve fedora performance issues that are preventing us from migrating to our Enterprise fedora (which was planned for this coming weekend, but which has been postponed). This non-official version might also lead us to a solution to #2118.

**Comment by cjcolvar** [comment]
@carrickr did you do enough of this that we could call it done?

**Comment by davidschober** [comment]
@mbklein and @carrickr your call on tossing it up on AWS staging. @carrickr you reported to the Fedora folks right?

**Comment by phuongdh** [comment]
It is on Mallorn now. Some quick testing looks good. Does it need a full regression suite?

**Comment by phuongdh** [comment]
At sprint planning we talked about having @Karthikeya212 run some load/performance test

**Comment by Karthikeya212** [comment]
I have completed the performance scenarios except bulk actions which will take some time to set up data and test. I have attached a document with the benchmark values for each scenario and its tested valued on fedora 4.7.4. The item load time is improved, but I see a slight lag for playlist performance.
[Avalon R6 Performance on Fedora 4.7.4.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a747faca210c2000ae4f77/125516c66e82c728ace21e0d46c9829b2f8d8de9bdbfff73a14ff69b3b4b267d2a01e3247ec5c52dbb4d69004f5b50ab5f5c4d58eeb9cb74fce36f34985619e8d6690975c46e18f8eb844dbe03ba278b4b80e7ea8d4cc6fa2137a5dad11b61435c52dcbd4f3fb29c4ac858fc4ae44d56ad10366be676357b478653.xlsx)

Will update the values for bulk actions after its done.

**Comment by phuongdh** [comment]
#2224 covers load testing 4.7.4, should we close this one?

**Comment by Karthikeya212** [comment]
Find the performance scenarios complete result set in the attached document.

[Avalon R6 Performance on Fedora 4.7.4.xlsx](https://github.com/avalonmediasystem/avalon/files/1265021/Avalon.R6.Performance.on.Fedora.4.7.4.xlsx)

**Comment by mcwhitaker** [comment]
@pdinh @carrickr  - How will the results of this testing be shared with the fedora folks?
