### ISSUE TITLE
MediaElement 4 Player - Structural metadata

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2161]
### Description
Incorporate structural metadata into section link clicking functionality.  

### Done Looks Like
- User can click on structural metadata links within sections and the MediaElement4 player behaves as expected; i.e., clicking a link will set the current position of the player to the beginning of the range defined by that segment of structure.

### Tasks
- [x] Discover object structure of structural metadata, and make sure that's getting passed into the MEJS Player JS wrapper.
- [x] Set up / adjust event listeners for structural metadata links.
- [x] Set up parsing of links to get start / end times.
- [x] Write start / stop time hooks into the player API.

**Comment by adamjarling** [comment]
@davidschober @joncameron Maybe someone can more fully describe what should happen here (from end user perspective).

Also, would it make sense to create a new 'mediaelement4' label, or some quick way to group these items?

**Comment by bkeese** [comment]
You can look at the way structural metadata is represented on the page here. Note the time offset parameters in the links. Those could also be represented as hh:mm:ss or mm:ss. https://pawpaw.dlib.indiana.edu/media_objects/02870v844
So, we'll just need to parse those then set the player's current time.

**Comment by davidschober** [comment]
Sure @adamjarling 

A user can add structural metadata to an object which allows them to navigate through a long master file. For instance if a symphony was digitized as a single file (3 hours), a collection manager could add start and stop times using our structural editor. The structure is represented as XML

![screen shot 2015-08-26 at 4 28 18 pm](https://user-images.githubusercontent.com/4803230/28321910-2ea278fe-6b9a-11e7-93e7-a74f171dad76.png)
![screen shot 2015-08-26 at 4 27 56 pm](https://user-images.githubusercontent.com/4803230/28321911-2ea3dbf4-6b9a-11e7-89dd-1fd1989691d2.png)


docs for the functionality are here: [docs for structural metadata editor](https://wiki.dlib.indiana.edu/display/VarVideo/Adding+Structure+to+Files+Using+the+Graphical+XML+Editor)

**Comment by adamjarling** [comment]
@davidschober @bkeese Thanks for the clarifications.  This helps.

**Comment by joncameron** [comment]
@adamjarling @davidschober I've created an Epic label, _MediaElement Upgrade_ and I'll try to get everything labeled soon.

**Comment by adamjarling** [comment]
@davidschober @joncameron @mcwhitaker @cjcolvar  This now works for navigating simple structural metadata, however if someone wants to point me to a few use cases for complicated structural metadata, I can make sure it holds up.  

The latest code is pushed to https://github.com/avalonmediasystem/avalon/tree/mejs4 if anyone would rather test locally.

**Comment by mcwhitaker** [comment]
@adamjarling Here are 2 manifests that represent the most complexity we can find in our current IU items.

http://dlib.indiana.edu/iiif_av/mahler-symphony-5/mahler-symphony-5-v2.json -- ranges 3 levels deep
http://dlib.indiana.edu/iiif_av/mixed-content/mixed-content-v2.json -- mixed content with structural metadata

**Comment by adamjarling** [comment]
Note this issue does not include the section highlighting in the player, or the current section arrows.
