### ISSUE TITLE
Test "hand rolled" version of fedora 4.7.4 reindex

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2180]
## Description

Avalon currently has issues reindexing everything due to the time it takes Fedora to start responding. Indiana is investigating and working with the Fedora folks to test a custom version of Fedora that has a proposed fix.

## Note
This is part of IU's internal points 

## Done Looks Like
Testing is done on custom Fedora version and reported back to Fedora team.

## Tasks

- [x] test custom Fedora version
- [ ] report results to Fedora team
- [ ] create a ticket for proposed solution

**Comment by davidschober** [comment]
@cjcolvar does this describe the work? Feel free to edit at will.

**Comment by phuongdh** [comment]
ActiveFedora does not know how to handle pairtree nodes. This won't work for us as-is. @cjcolvar can you update this story with the Fedora ticket when it's created?

**Comment by cjcolvar** [comment]
Ticket created: https://jira.duraspace.org/browse/FCREPO-2544
