### ISSUE TITLE
MediaElement 4 Player - Highlight Current Segment on Rail

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2184]
### Description
Porting the same behavior as currently exists in the MediaElement 2 player in Avalon to MediaElement 4.

### Done Looks Like
When the playhead is within the time defined by a track (segment) of file-level structural metadata, the player shows that portion of time highlighted on the rail.

### Example of Current Look
![screen shot 2017-08-01 at 11 48 33 am](https://user-images.githubusercontent.com/1406618/28834126-7115d99a-76af-11e7-8b92-e1f425de7baf.png)

### Tasks
- [x] Verify the highlighted range is driven by CSS.
- [x] Investigate how the range timing/length/display is calculated.
- [x] Create / Re-use the CSS styling for highlighted segments.
- [x] Create handlers in new MEJS4 JS wrapper to calculate and display highlighted segments.

**Comment by davidschober** [comment]
this looks redundant to #1879.

**Comment by mcwhitaker** [comment]
@davidschober If I understand correctly, #1879 refers to the lil' scrubber and this is the main scrubber.

**Comment by cjcolvar** [comment]
This is looking pretty good on spruce for user initiated structure clicks but I'm not seeing the highlight update when the current play time moves into a new segment or when the user clicks on the scrubber.  Also when the player loads for https://spruce.dlib.indiana.edu/media_objects/mp48sc84s?mejs4=true it looks like it is highlighting the Introduction segment (both Part 1 and Part 2) instead of just the first leaf node (Part 1).

**Comment by adamjarling** [comment]
@cjcolvar Yes, you're correct.  I'm working on that side of things now in #2391 Kind of taking things in pieces.
