### ISSUE TITLE
Developer instructions for testing with canvas

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2210]
### Description
As a developer I want to be able to test LTI integration with canvas without involving central IT.  A docker container exists for canvas which might be able to be used within a local development environment to quickly spin up and test against.  Otherwise, we could install canvas on a testing machine like spruce or mallorn and make it easy to configure for local development instances of avalon to use.

### Done Looks Like
Instructions written for testing LTI with local development environment.

### Tasks
- [x] Install test canvas instance on a testing server
- [x] (If necessary) Try out canvas docker container in a local dev environment
- [x] Configure development environment to point to canvas instance
- [x] Run manual tests to ensure that everything is working
- [x] Document process for testing for developers

**Comment by cjcolvar** [comment]
lti.yml that works for me in my local dev environment setting up for fluorine canvas:
```
794d72b707af6ea82cfe3d5d473f16888a8366c7.localhost:3000:
  :uid: :tool_consumer_instance_contact_email
  :email: :tool_consumer_instance_contact_email
  :context_id: :context_label
  :context_name: :context_label
```

**Comment by cjcolvar** [comment]
Draft written here: https://github.com/avalonmediasystem/avalon/wiki/Testing-LTI-integration-with-Canvas

**Comment by phuongdh** [comment]
Currently not working with Spruce. I will look at it more today.

**Comment by phuongdh** [comment]
Works for Spruce and @cjcolvar 's local dev but not working for me. Likely some misconfiguration in my environment, closing unless someone else runs into it.

NoMethodError (undefined method `[]' for nil:NilClass):
  app/controllers/users/omniauth_callbacks_controller.rb:72:in `find_user'
  app/controllers/users/omniauth_callbacks_controller.rb:43:in `action_missing'


  Rendered /home/app/gems/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.2ms)
  Rendered /home/app/gems/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.9ms)
  Rendered /home/app/gems/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /home/app/gems/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (19.7ms)
