### ISSUE TITLE
Optimize queues and workers allocation

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2238]
Long running jobs can hold up Resque workers, leaving the important jobs in pending state. For example: while deleting a 100-section item, your ingest job will take forever to start.

One possible solution: multiple workers are started and allocated to different queues in away that jobs are not held up. Long running jobs should have their own queue(s) instead of the default one.

- How many workers do we need?
- What queues are those workers listening to?

### Done looks like

- Recipe page in documentation written for handling allocation of workers and queues.

### Tasks
- [ ]  Discussion of what this recipe contains
- [ ] Apply this recipe to Spruce and Mallorn
- [ ]  Page written in Wiki

**Comment by phuongdh** [comment]
Try to rate limit create_jobs so Matterhorn doesn't bog down responding to them https://github.com/malomalo/resque-throttler

**Comment by joncameron** [comment]
Abandoned—work has been done with Sidekiq that fulfills this.
