### ISSUE TITLE
6.2. Code Freeze and Merge

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2257]
### Description
Code merges, update and cleanup for the public release of 6.1.

### Tasks

- [x] Update version in code
- [x] Update license headers in files
- [x] Tag dependency repos
- [x] Update gemfile to point to those tags
- [x] Merge to staging branch
- [x] Staging pushed to Mallorn for testing

#### Post Testing
- [x] Merge 6.2rc into master
- [x] Create tag for v6.2.0

**Comment by lealeelu** [comment]
The license headers don't need to be updated since they already say 2017.

**Comment by joncameron** [comment]
@lealeelu Is there any more review needed for this, or is it ready to be closed?

**Comment by lealeelu** [comment]
It's all done.
