### ISSUE TITLE
6.2 - Public Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2258]
### Description
Releasing 6.2 to the world after code work in #2257 is competed.

### Tasks
- [x] Write a draft of release notes on Github
- [x] Publish release on Github https://github.com/avalonmediasystem/avalon/releases
- [x] Update wiki with release notes as needed
- [x] Publish blog post announcing the release
- [x] Put announcement on Twitter and Facebook
- [ ] Send out email to Samvera community mailing list
- [ ] Publicize in appropriate Slack channels
