### ISSUE TITLE
Investigate MediaElement4 Unit/Feature Testing

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2280]
### Description
Taking a look at the latest MediaElement, how it's being incorporated into the page, and figuring out the best way to test it.

Determine the best approach (Rails integration tests) and/or Jest to unit test the new JavaScript MEJS4 wrapper file and plugin files directly.

### Tasks
- [ ] Use Jest (possibly) as the testing framework
- [ ] Rails integration tests ( click here, expect to see this on screen, etc. )
- [ ] Make decision on approach

@joncameron @davidschober @cjcolvar @mbklein

**Comment by davidschober** [comment]
discussion during BB. This code would be useful for Avalon 7. @lealeelu can help write tests.

**Comment by adamjarling** [comment]
#2573 should be completed first, then work on this issue.

**Comment by joncameron** [comment]
This can leave open, but may need to be written and re-evaluated.

**Comment by joncameron** [comment]
@adamjarling Should we go ahead and abandon this? At a minimum we'll remove it from the scope of 7.0 release.

**Comment by adamjarling** [comment]
Yea, it probably needs to be re-framed with what player we're using, where.  I'd close it.

**Comment by davidschober** [comment]
abandoned
