### ISSUE TITLE
Test Fedora Changes for Reindexing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2290]
### Description 
Reindexing in Avalon has poor performance in instances with a large number of Fedora objects  due to the reasons brought up in this issue: https://jira.duraspace.org/browse/FCREPO-2544. These changes need to be tested to see how the performance differs when performing reindexing tasks.

### References
- Original JIRA Story: https://jira.duraspace.org/browse/FCREPO-2544
- Fedora PR: https://github.com/fcrepo4/fcrepo4/pull/1223

### Tasks
- [ ] Determine which approach(es) below to test
- [ ] Make PR to ActiveFedora with preferred approach (including documentation)
#### N-Triples Serialization
- [ ] Modify ActiveFedora to accommodate the change
- [ ] Test reindexing
#### PairTree Prefer Header
- [x] Build Fedora from PR
- [ ] Modify ActiveFedora to accommodate the change
- [ ] Test reindexing

**Comment by cjcolvar** [comment]
Some notes on testing from Andrew Woods:
https://samvera.slack.com/archives/C1N4Y4H8D/p1504677642000004

**Comment by phuongdh** [comment]
WAR file built at https://slashtmp.iu.edu/files/download?FILE=pdinh%2F73762YrygvJ, pass: archivist1

**Comment by joncameron** [comment]
Might depend on IU's timeline; possibly two weeks from now until we're able to think about this and to begin testing. This is because of the need to test this on IU's staging instance, but NU could also put resources in if available.

Another ticket could be written to indicate the ActiveFedora changes that need to be made and tested.

**Comment by joncameron** [comment]
We probably need a timebox (maybe a 2) to figure out how long this will actually take, and then decide when to tackle this based on that.

**Comment by cjcolvar** [comment]
I commented on the fedora ticket with numbers from running with the "Accept: application/n-triples" header.  I also kicked off an avalon:reindex task on sodium with ActiveFedora monkey-patches to use this header, but ran into an exception probably dealing with malformed data or a fedora issue: https://gist.github.com/cjcolvar/d7a7953f8c827f106d561c2b447712e7

**Comment by davidschober** [comment]
@cjcolvar is this still valid? Or did this get abandoned? I tagged with 6.x not 6.3

**Comment by cjcolvar** [comment]
This is still valid and is still left hanging as a TODO on each fedora tech call.  It was also discussed a couple weeks ago on slack.  It would be really great to get back to this!

**Comment by cjcolvar** [comment]
The Fedora issue has been closed and I just created an AF PR: https://github.com/samvera/active_fedora/pull/1300

**Comment by cjcolvar** [comment]
We should also consider if we need to incorporate the monkey-patch into Avalon 6.x or if the PR is merged into AF soon if we'll upgrade AF for the next 6.x release.

**Comment by cjcolvar** [comment]
@mbklein tested and the AF PR has been merged.
I'll make a new ticket for applying this change to Avalon 6.x.
