### ISSUE TITLE
Decide on best way to deal with remote master files

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2298]
### Description 

This story informs #2291. We want to allow master files to be loaded from other remote services (box, etc). In order to do this we have to decide the best way to ID and transcode said files. We learned from our work with hyrax and very large data sets that moving to local storage might not be the best solution (move to local storage, stream, have someone run up the master files on a thousand floppy disks).

### Done looks like
A Decision is made on how to ingest remote master files and tasks are written in #2291.

### Tasks
- [ ] Determine which remote services we plan to support (in order to know what url schemes to support)
- [ ] Determine which url schemes `mediainfo` supports
- [ ] Determine which url schemes the Matterhorn ActiveEncode adapter supports
- [ ] Determine which url schemes the Amazon Elastic Transcoder ActiveEncode adapter supports
- [ ] Write tasks for #2291
