### ISSUE TITLE
MEJS4 - Playlists page playlist items list

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2308]
### Description
On the playlists page, the playlist items list in the upper right hand corner needs to be wired up to MEJS4.

### Done Looks Like
- Current MEJS2 player functionality / interactions with the playlist items list works the same with the MEJS4 player.

### Tasks
- [x] Bypass current method of loading MEJS2 player when clicking on an item.
- [x] Create (possibly) a new JS file which will wrap interactions with this list of items.
- [x] Hook into the MEJS4 JS wrapper file to destroy and re-instantiate a new player depending on what media type each link refers to.
- [ ] More detailed tasks to come as I dig into this a bit and understand what's currently happening...

### More detailed tasks
- [x] Create routes for mejs4_markers, mejs4_source_details, mejs4_related_items
- [x] Create 3 new partials for the 3 routes
- [x] current marker partial copied and re-worked to return new markup
- [x] source_details and related_items use current partials for now

![playlists-playlist-items](https://user-images.githubusercontent.com/3020266/30296692-a3c2e010-970a-11e7-83dc-2c2e9f61c090.png)

**Comment by jlhardes** [comment]
Pairing with @lealeelu and maybe @bkeese

**Comment by adamjarling** [comment]
The markup for the "Markers" partial .html file:
```
<div id="markers" class="container">
  <div id="marker_item_edit_alert" class="mejs-form-alert alert alert-danger" style="display: none;">
  <p></p>
  </div>

  <table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th class="text-right">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr data-offset="10.0" data-marker-id="15">
      <td>
        <a class="marker_title display-item outline_on" data-offset="10.0">10 second marker</a>
        <input name="title_15" type="text" class="form-control edit-item outline_on" value="10 second marker">
      </td>
      <td>
        <span class="marker_start_time display-item">00:10</span>
        <input name="offset_15" type="text" class="form-control edit-item outline_on" value="00:10">
      </td>
      <td class="text-right" id="popover-container-15">
        <button name="edit_marker" type="button" class="btn btn-default btn-xs edit_marker display-item outline_on">
          <i class="fa fa-edit" title="Edit"></i> <span class="sm-hidden">Edit</span>
        </button>                
        <button name="save_marker" type="button" class="btn btn-default btn-xs edit-item outline_on">
          <i class="fa fa-check" title="Save"></i> <span class="sm-hidden">Save</span>
        </button>                
        <button name="marker_edit_cancel" type="button" class="btn btn-danger btn-xs edit-item outline_on">
          <i class="fa fa-times" title="Cancel"></i> <span class="sm-hidden">Cancel</span>
        </button>                
        <button data-marker-id="15" name="delete_marker" class="btn btn-danger btn-xs display-item outline_on">
          <i class="fa fa-times" title="Delete"></i> <span class="sm-hidden">Delete</span>
        </button>
      </td>
    </tr>
    <tr data-offset="18.0" data-marker-id="16">
      <td>
        <a class="marker_title display-item outline_on" data-offset="18.0">18 second marker</a>
        <input name="title_16" type="text" class="form-control edit-item outline_on" value="18 second marker">
      </td>
      <td>
        <span class="marker_start_time display-item">00:18</span>
        <input name="offset_16" type="text" class="form-control edit-item outline_on" value="00:18">
      </td>
      <td class="text-right" id="popover-container-16">
        <button name="edit_marker" type="button" class="btn btn-default btn-xs edit_marker display-item outline_on">
          <i class="fa fa-edit" title="Edit"></i> <span class="sm-hidden">Edit</span>
        </button>                
        <button name="save_marker" type="button" class="btn btn-default btn-xs edit-item outline_on">
          <i class="fa fa-check" title="Save"></i> <span class="sm-hidden">Save</span>
        </button>                
        <button name="marker_edit_cancel" type="button" class="btn btn-danger btn-xs edit-item outline_on">
          <i class="fa fa-times" title="Cancel"></i> <span class="sm-hidden">Cancel</span>
        </button>                
        <button data-marker-id="16" name="delete_marker" class="btn btn-danger btn-xs display-item outline_on">
          <i class="fa fa-times" title="Delete"></i> <span class="sm-hidden">Delete</span>
        </button>
      </td>
    </tr>
  </tbody>
  </table>
</div>
```

**Comment by bkeese** [comment]
New routes are:
```/playlists/:playlist_id/items/:playlist_item_id/markers(.:format)        /playlists/:playlist_id/items/:playlist_item_id/source_details(.:format) /playlists/:playlist_id/items/:playlist_item_id/related_items(.:format) 
```
