### ISSUE TITLE
As a tester I should be able to test canvas on Fluorine with Student accounts

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2334]
### Description
As a tester I should be able to add the students to the canvas site on Fluorine to test the LTI access. As of now it has only a Teacher account canvas@example.edu

### Done Looks Like
Tester has credentials and documentation for LTI testing on Fluorine.

### Tasks
- [x] Student accounts are created for the Canvas instance on Flourine
- [x] Wiki page created to hold information about the Canvas test instance, with server name/port and credentials
- [x] Credentials passed to QA or posted on the wiki

**Comment by davidschober** [comment]
@phuongdh is this pretty straight forward?

**Comment by Karthikeya212** [comment]
Tested and student access is working fine

**Comment by phuongdh** [comment]
Doc added to bottom of page https://github.com/avalonmediasystem/avalon/wiki/Testing-LTI-integration-with-Canvas
