### ISSUE TITLE
Support Multiple Caption Files per MasterFile

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2346]
# Description
As a collection manager, I want to upload multiple caption files for a single masterfile so that any number of caption files (for example, multiple caption files per video corresponding to different languages) can be selected and used during playback. Each caption file should have an associated label.

# Language Field
* Avalon yml contains the language values for ISO639-2; these can be used for indicating the language
* What UI element does this use? drop-down list, typeahead form field...

# Done Looks Like
- Users can upload multiple caption files per masterfile from the "Manage Files" page
  - Caption files are managed in the UI in an identical way to Transcript files (with a label field)
  - Specify the language of the caption file through a UI element upon upload (typeahead suggested)
  - List of caption files in player should use label (defaults to filename) rather than language

### Tasks
- [x] Ensure model can hold multiple captions files. Make changes/migrations as necessary
- [x] Change Structure Edit page to allow management (upload/remove) of multiple captions files
- [x] Evaluate if MediaElement works by default with added caption files present (if this does not work, revert to the existing behavior of using a single caption source)

**Comment by joncameron** [comment]
ME can probably handle this out of the box—bulk of the work being the structure edit page and how they're attached to a media object.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners is this meant for 6.x or 7.x?

**Comment by elynema** [comment]
Note that if this work is included in 7.7, we'll need to have data migration as part of the upgrade process.

**Comment by masaball** [comment]
File upload page should provide a typeahead/drop down field for language selection, similar to the language field in the Resource Description step. 

@joncameron thinks it is fine to have the caption label field default to the filename.

**Comment by elynema** [comment]
@masaball I think the label is helpful, especially for the Language drop-down which might not be entirely clear otherwise. @joncameron Do you have opinions?

**Comment by joncameron** [comment]
Let's definitely include the label. Could it be just a single label row at the top, rather than repeat for each row? With the current layout having a header label row seems like all that would be needed.
