### ISSUE TITLE
IIIF Avalon Player - Explore Manifesto for parsing

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2355]
### Description
Look into manifesto (https://github.com/viewdir/manifesto) to see if we can leverage their parsing functionality. 

### Tasks
- [ ] Browse through code, see how manifesto works.
- [ ] Evaluate whether manifesto's parsing will help us in the latest mallorn generated manifests.
- [ ] If it supports IIIF Presentation 3.0 (and our use cases), use the library.
- [ ] Possibly see how we could contribute / be a part of future manifesto parsing work, and potentially establish or learn about patterns which client side apps can use when consuming 3.0 A/V manifests

**Comment by davidschober** [comment]
@adamjarling did we go another way with this?

**Comment by adamjarling** [comment]
Haven't touched this yet.  I don't thing Manifesto yet supports the 3.0 spec, at least as of a month ago, and the spec has evolved since then.   This is probably a longer term, when we have to time to jump back into the IIIF player, issue.   But good to keep on the radar.

**Comment by davidschober** [comment]
I'm going to abandon this to clean up the board. We can attack this as we get into 7.0 dev.
