### ISSUE TITLE
MEJS4 - Handle section transitions in JS wrapper

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2391]
### Description
The new JS wrapper file needs to be aware of transitioning sections from the structural metadata links.   It needs to know what the current section (playing) is, and it needs to handle section transitions.

### Done Looks Like
MEJS4 playing section to section (on the media object display page, not playlists (yet)), should be same behavior as the MEJS2 player.

### Tasks
- [x] Identify current section and represent this in the JS.
- [x] Programmatically determine/handle section transitions. For example figure out how the player knows a current section has ended, or a new one has begun.
- [x] Bind section transitions to UI (ex. un-highlighting a section, highlighting a section when the player reaches the start point, etc.)

**Comment by adamjarling** [comment]
@cjcolvar @bkeese  For the media object view page, is there any straightforward way to construct the Sections links data attributes `<li class="stream-li"><a data-abc data-xyz` as an array of objects which we could pass to the MEJS wrapper javascript file?  I'm looking in the `app/helpers/media_objects_helper.rb` file, but can't seem to figure out if that method exists, or how hard it'd be to construct the array.   Maybe I'm missing something.

My other path is to crawl the DOM and construct the array of objects, but that seems a little redundant.

![avalon-sections.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e9829b2f8d8de49cecbc57ad52fe876b0a65633b0ba92e7391a172fd172c55095e4cff480c0c42aef88b2ba1b63875db0a0cedd77f4366846c4ff8e7df46f554f832815d84beb68b49c0e03f22e38a89463e1f020ac4.png)

**Comment by bkeese** [comment]
Currently there is no such method. We just walk the tree of the structural_xml and generate the dom from that.  But it could be refactored to generate a js data structure that the client then walks to generate the dom. Or, it could do both.

**Comment by adamjarling** [comment]
Ok, just checking.  I'm trying to think of an alternate way to shrink the amount of code executed on each MEJS `.on('timeupdate', () =>)` callback.  That's a lot of continuous processing, displaying the highlighted sections, but maybe no easier way to do it.  Thanks for the feedback... I'm going to keep messing with it, and if it seems there's a need for a JS structure object that'd help I'll reach back out.

**Comment by adamjarling** [comment]
@bkeese Not sure if this helps, but since you mentioned you were thinking about this topic at standup, here's what would help the front-end (at least where my heads at now).  This could also be done in the future, as an enhancement.  Just tracking some thoughts on how to optimize while I'm in it.

1. The js wrapper knows what the "current playing segment" is (or knows there is not an active current segment to display in the time rail).  I'm creating a custom property on the player instance to track this.

2. Each segment has a unique identifying value in it's `<a>` or parent `<li>`.  Preferably an `id`attribute for fast DOM lookup.

3. In the player instance's `timeupdate` callback function (which happens around once per second if not more), the code checks 
  a.) if there's a current segment value on the player, and if so, does nothing.  Or,
  b.) If there's no current segment value on the player instance, the code checks an array of objects (representing the DOM segment links) to see if the current time falls within any of the ranges.   If so, it calls methods which update the DOM UI, and saves the current segment on the player instance.

Hopefully this is not too confusing.   This is the general approach I'm taking, and happy to share where I'm at at any point today if you're curious.

**Comment by bkeese** [comment]
@adamjarling It should be pretty easy for the server to add an id for each segment that you can use for lookups. 
For #3, I don't think your algorithm is quite right. The code will need to check for current segment for every timeupdate event. Otherwise, it won't know when it has gone past the end of the current segment.
Are you ok with the player generating the array of segment objects upon load? If not, we can generate some js on the server side.

**Comment by adamjarling** [comment]
@bkeese Yea, I actually updated the helper it to give the element an id.  Working on some stuff and will run it by you tomorrow, see if the logic is right.
