### ISSUE TITLE
Update Mailers to Use a Single Consistent Email Address

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2408]
### Description
On AWS you can only send from verified emails (that is AWS has sent you a link to click and verify you control the email address).  So our practice of sending contact form feedback with the from address being whatever the user puts into the form doesn't fly on AWS.

### Done Looks Like
- _From_ should come from a single configurable address (re-use existing system address?)
- _Reply-to_ should be the address entered into the contact form (user's email)

### Tasks
- [ ] Update All Mailers to use one uniform from address
- [ ] Update the comment mailer to include the user's email address in the body (since it is no longer in the from field)
- [ ] Document the need to go into and verify the address when running on AWS (the from address is an Avalon environment config, so you can stick in anything, you just have to verify it via Amazon Simple Email Service)

**Comment by davidschober** [comment]
@carrickr can w set the "Reply to" without verifying. http://docs.aws.amazon.com/ses/latest/DeveloperGuide/email-format.html

It's unclear from the docs. At a minimum we need to document that the  return path should be set to a box a user has access to for the purposes of tracking bounces.

**Comment by carrickr** [comment]
@davidschober easiest way to be to test it on our staging probably.

**Comment by carrickr** [comment]
MBK tested it and reply-to does work, although we do have to be aware that not all clients respect it.  So we may still want to include it in the body and also be sure to call out the use of reply-to.

**Comment by davidschober** [comment]
That sounds good.

**Comment by joncameron** [comment]
@mbklein Can we re-use what you already did for this?

**Comment by carrickr** [comment]
@joncameron @davidschober 

Commit is in, as a documentation note:

The mailer will set reply-to be the email the the user supplied.  However from will always be from whatever is set in `settings.yml` for your comment email:
```email:
  comments: 'avalon-comments@example.edu'```

AWS makes you prove you 'own' that email by sending an email to it with a link you have to click to prove you own the email.  So that is a set that needs to be added to our setting up AWS doc set.

The second import note is that not all email clients respect reply-to.  So when someone responds to a comment they need to make sure that when they click reply it sends to the user, not `avalon-comments@example.edu`/whatever was set.  The body of the email also lists the email address of the user.  For folks whose clients don't respect reply-to, they will need grab the email address from the email body and stick it in.

**Comment by joncameron** [comment]
@phuongdh What's the best documentation page to put carrick's last comment under?
