### ISSUE TITLE
IIIF Manifests: update our sample manifests 

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2419]
### Description
Our IIIF sample manifests (https://github.com/avalonmediasystem/avalon-iiif-player/wiki/IIIF-AV-Sample-Manifests) are out of date given the recent changes to the Presentation 3 spec. It would be helpful to keep a good sample list of manifests not only for us but also for those who refer to our current work with IIIF.

### Done Looks Like
The manifests on our Sample Manifests list are updated.

### Tasks
- [ ] Identify which manifests make sense to keep on that page
- [ ] Use mallorn to recreate those manifests
- [ ] Post those manifests (accessible publicly)

**Comment by mcwhitaker** [comment]
Cannot use mallorn to recreate the manifests since not all the content is in mallorn. 

Mallorn manifests will point to the media files in mallorn. @cjcolvar will those files be accessible if other IIIF clients try to test using our manifests and play them? For our dlib folder for web sharing, we had to set up CORS for them to be available. Is mallorn setup for that?

**Comment by mcwhitaker** [comment]
I have manually recreated the video manifests listed on our Sample Page. I will keep this ticket open for another sprint, but can't deal with all the other manifests right now.
