### ISSUE TITLE
6.3 Release - Public Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2466]
### Description
Releasing 6.3 to the world.

### Tasks
- [x] Write a draft of release notes on Github
- [x] Publish release on Github https://github.com/avalonmediasystem/avalon/releases
- [x] Update wiki with release notes as needed
- [x] Publish blog post announcing the release
- [x] Update front page of website with 6.2 announcement and any other website pages with references to 6.2
- [x] Put announcement on Twitter and Facebook
- [x] Send out email to Samvera community mailing list
- [x] Publicize in appropriate Slack channels

**Comment by davidschober** [comment]
@joncameron @cjcolvar  it sounds like we're good with 6.3.2 Can someone tag it?

**Comment by cjcolvar** [comment]
@davidschober we need to make a PR from staging to master and then tag master after that has been merged.
