### ISSUE TITLE
6.3 Release - Code Freeze and Merge

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2467]
### Description
Code merges, update and cleanup for the public release of 6.3.

### Tasks

- [x] Update version in code
- [x] Update license headers in files
- [x] Tag dependency repos
- [x] Update gemfile to point to those tags
- [x] Merge to staging branch
- [x] Staging pushed to Mallorn for testing

#### Post Testing
- [x] Merge 6.3rc into master
- [x] Hit the release button in Github
- [x] Create tag for v6.3.0 (should already happen with hitting release button)

**Comment by phuongdh** [comment]
I think dependency repos look good, most are mejs2 plugins, they don't need retagging.

**Comment by cjcolvar** [comment]
I think we can make the merge to staging once we've got these last few PRs in.  Smoke test on mallorn then make the PR to master.

**Comment by phuongdh** [comment]
Moving this to done since it's completed
