### ISSUE TITLE
MediaElement4 - Mobile/Tablet verify functionality

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2478]
### Description
After all the work to MEJS4, make sure all works as expected on mobile/desktop.

### Tasks
- [ ] Check benchmark functionality in Browserstack, using Spruce or Mallorn URL.
- [ ] Check on actual (real) devices.
- [ ] Create tickets from broken functionality and/or display issues.

**Comment by adamjarling** [comment]
@davidschober @joncameron FYI, this will need to be addressed towards end of MEJS4 work.

**Comment by davidschober** [comment]
@adamjarling I'll move it to ready, can you take a stab at points?

**Comment by cjcolvar** [comment]
Testing on physical device 4th Gen iPad running iOS 10.3.3: https://github.com/avalonmediasystem/avalon/issues/2609
