### ISSUE TITLE
MEJS4 - Add Spinner to player / page interactions

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2483]
### Description
We should implement a spinner to give user feedback that things are processing when interacting with the MEJS4 player.  Such as when adding a marker, updating a marker, or in cases when clicking on a section loads a new player (ie. audio player from a video player).

### Tasks
- [x] Does an Avalon spinner current exist?
- [x] If not, create a spinner.
- [x] Implement the spinner via CSS and into the JS player wrapper.

**Comment by adamjarling** [comment]
@davidschober @joncameron

**Comment by joncameron** [comment]
@adamjarling 
Yes, this would be great. We don't have a spinner currently; the behavior right now is that the player sort of freezes with timecodes displaying 0:00, then resizes and updates the time with info from the media server once things are loaded. I don't think there's any feedback for interactions like adding or updating markers, delays while the streaming server responds to a seek, etc.

Were you the person who implemented the spinner for the NU instance?
![spinner](https://user-images.githubusercontent.com/1406618/33486517-600ab430-d678-11e7-9fdc-d9d23e036404.gif)
Would it be possible to use or modify that for core Avalon?

**Comment by adamjarling** [comment]
This is now in place for Playlist Items page `#accordion` panel section when pulling new data via ajax to the page.

**Comment by adamjarling** [comment]
@joncameron @davidschober If either of you want to have a look at this and see if it looks ok?  If you go to the Playlists Items page, and have multiple playlist items, you'll notice the spinner over the Markers accordion panel (if its expanded), as the playlist items go from one to the next.

**Comment by davidschober** [comment]
I think that looks good. I'm assuming you put it low because you have to be low on the page to move from item to move from item to item in mobile view. @joncameron Is this good with you?

**Comment by joncameron** [comment]
@davidschober @adamjarling  I love it! Looks great.

**Comment by adamjarling** [comment]
@davidschober Re: putting it low... There's already a default MEJS spinner for loading video content in the player itself.  The asycn data we're pulling in is the "Markers Row" table.  So that was the motivation.  Indicating that content might not be accurate until the spinner is gone and the new markers table rows have loaded into the page.

Originally we used a custom spinner over the player itself, but this was because of a weird Chrome syncing issue.  Hopefully that doesn't re-surface now?

**Comment by davidschober** [comment]
Sounds good.
