### ISSUE TITLE
Bugs to Break Out

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2503]
# Issues reported by Chris and Phuong

## Playlist
- [ ] Adding new marker refreshes page losing context like current playlist item and play time
- [ ] Markers not showing on scrubber
- [ ] Switching between playlist items doesn't change video source
- [ ] Autoplay not working in playlists
# Item player
- [ ] Playling canvas is wider than player background and hangs off a little on the right (covered by https://github.com/avalonmediasystem/avalon/issues/2266 ?)
- [ ] Quality control missing tooltip text
- [ ] Playthrough on item view page not working
- [ ] Can't navigate into player via keyboard (from either before or after in the DOM) (https://github.com/avalonmediasystem/avalon/issues/2130)
- [ ] Escape key doesn't close thumbnail grabber modal (https://github.com/avalonmediasystem/avalon/issues/2130)
- [ ] Thumbnail grabber submit doesn't refresh the player page (won't fix?)
## Embed player
- [ ] Embedded player size needs to be the same as the MEJS2 player
- [x] Embed missing title plugin (in progress in https://github.com/avalonmediasystem/avalon/issues/2096)
- [x] Embed missing info icon link to repository plugin (in progress as part of https://github.com/avalonmediasystem/avalon/issues/2096)
- [ ]  Little scrub much bigger than in MEJS2
- [ ] Poster image is cropped width-wise

**Comment by davidschober** [comment]
redundant with #2504
