### ISSUE TITLE
Adding new marker refreshes page losing context

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2505]
## Description

when adding a new marker, the page refreshes and the user looses context such as  current playlist item and play time. 

### Tasks
- [ ] Verify this is an issue when there are no markers, and user creates their first marker.
- [ ] Dig into why a page refresh is necessary (refresh my memory)
- [ ] See if we can update the HTML markup for the accordion panels with the new REST end points.

**Comment by davidschober** [comment]
@adamjarling and @cjcolvar Did this get completed with other work? I'm not seeing this on spruce in Safari or Chrome.

**Comment by adamjarling** [comment]
I think this happens when there are no current markers (like you're adding the first one), I have it set to do a page refresh.  But now with some new endpoints created, we might be able to just pull that markup in via the REST endpoint instead of the trying the page refresh route.

**Comment by davidschober** [comment]
Ah! OK.

**Comment by davidschober** [comment]
@adamjarling you want to size it and move it ready?

**Comment by adamjarling** [comment]
Sure.

**Comment by adamjarling** [comment]
I looked at this this morning, and the motivation behind doing the page refresh is that the `<panel>` area for Markers is not yet in place when no markers exist, so there'd be a lot of HTML/markup building in the JS.  

Perhaps we could build from the endpoint @bkeese created which returns content for the `<panel>` section(s), and create an additional endpoint which returns the entire panel markup section?  Then we could keep the JS clean, keep the template file as a Rails template and just reference it.

Thoughts?

**Comment by adamjarling** [comment]
The return HTML would look like this:
```
<div class="panel-heading" role="tab" id="markers_heading">
      <h5 class="panel-title ">
        <a href="#markers_section" class="accordion-toggle pull-left" data-toggle="collapse" aria-expanded="true">
          Markers</a>
        </h5>
      </div>
<div id="markers_section" class="panel-collapse collapse in" role="tabpanel" aria-expanded="true" style="">
        <div class="panel-body">
            
<div id="markers" class="container">
  <div id="marker_item_edit_alert" class="mejs-form-alert alert alert-danger" style="display: none;">
    <p></p>
  </div>

  <table class="table table-condensed">
    <thead>
      <tr><th>Name</th>
      <th>Time</th>
      <th class="text-right">Actions</th>
    </tr></thead>
    <tbody>
          <tr data-offset="13.0" data-marker-id="93">
            <td>
              <a class="marker_title display-item" data-offset="13.0">13 seconds</a>
              <input name="title_93" type="text" class="form-control edit-item" value="13 seconds">
            </td>
            <td>
              <span class="marker_start_time display-item">00:13</span>
              <input name="offset_93" type="text" class="form-control edit-item" value="00:13">
            </td>
            <td class="text-right" id="popover-container-93">
                <button name="edit_marker" type="button" class="btn btn-default btn-xs edit_marker display-item">
                  <i class="fa fa-edit" title="Edit"></i> <span class="sm-hidden">Edit</span>
</button>                <button name="save_marker" type="button" class="btn btn-default btn-xs edit-item">
                  <i class="fa fa-check" title="Save"></i> <span class="sm-hidden">Save</span>
</button>                <button name="marker_edit_cancel" type="button" class="btn btn-danger btn-xs edit-item">
                  <i class="fa fa-times" title="Cancel"></i> <span class="sm-hidden">Cancel</span>
</button>                <button data-marker-id="93" name="delete_marker" class="btn btn-danger btn-xs display-item">
                  <i class="fa fa-times" title="Delete"></i> <span class="sm-hidden">Delete</span>
                </button>
            </td>
          </tr>
    </tbody>
  </table>
</div>


        </div>
      </div>
```

**Comment by cjcolvar** [comment]
I'm not really liking it.  I wonder if we could avoid this endpoint somehow.  Maybe the markers panel always shows?  @joncameron @davidschober any thoughts?

**Comment by bkeese** [comment]
Couldn't the current markers end-point just return a bit more (the whole panel)? We'd just need to adjust the current use of the endpoint to accommodate this change.

**Comment by joncameron** [comment]
My preference would be to have the markers panel not show unless markers exist, but if that was the only reasonable solution I'm fine with it. 

Could the markers_heading div be hidden until populated?

**Comment by cjcolvar** [comment]
@joncameron I was wondering that as well.

**Comment by adamjarling** [comment]
One solution along these lines would be that the backend creates the Markers panel HTML and puts it in the page when no markers exist.  Currently this doesn't seem to be the case, or when no markers exist that block of markup never gets to the DOM on initial render.

So guessing there's a check someplace on the Rails end?  That code could just put a "hidden" class, or `style="display:none"` on `<div id="markers_heading">` and `<div id="markers_section">`.

Then the JS, when it makes the endpoint call to get updated markup, can check whether those elements are being displayed or not and make them visible if necessary.

**Comment by cjcolvar** [comment]
@adamjarling I'll take a pass at making that change on both ends.
