### ISSUE TITLE
Playlist Items Page - Related panel content list wire up

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2529]
### Description
In the playlist items page the "Related" accordion panel body has a list of related (if they exist) playlist items.  We need to wire-up clicking on each item.

### Done Looks Like
- Clicking on a playlist item title in this list will act the same as clicking a playlist item in the right sidebar.

### Tasks
- [x] Add click listeners to the playlist items in the Related panel content.
- [x] Handle the click listeners in this file: `app/assets/javascripts/media_player_wrapper/mejs4_plugin_playlist_items.es6`
- [x] Hook into existing functions to achieve expected behavior.

@davidschober @joncameron
