### ISSUE TITLE
Playlist items page: Autoplay

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2533]
### Description
Clarify Autoplay behavior in playlist items page and implement in the app.

### Done Looks Like
- Mimics YouTube.  The player plays from one playlist item to the next with no user interaction.
- User interaction such as clicking on playlist items in the list, or clicking in range outside of current playlist item clip, will turn Autoplay "off".

### Tasks
- [x] By default Autoplay is on.
- [x] Don't advance to next item if Autoplay off
- [x] The player will set current time to the beginning of the playlist item start time
- [x] Do not play automatically on page load.
- [x] Handle click events in playlist items in sidebar to turn Autoplay "off".
- [x] Handle click events in the time rail, outside of current clip range, to turn Autoplay "off".

@davidschober @joncameron

**Comment by davidschober** [comment]
See my comment on #2534 If we have to add to both, can it be a single UI/ UX (and hopefully less work)

cc: @joncameron
