### ISSUE TITLE
Incorporate Prettier JS code formatting for code quality

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2535]
### Description
Run Mediaelement4 JavaScript files through the Prettier code quality tool.

### Tasks
- [ ] Developer install Prettier locally, globally.
- [ ] Create `.prettierrc` config file and commit to Avalon project which local devs can hook into.
- [ ] Run all `.es6` code through Prettier to clean it up and make consistent.
