### ISSUE TITLE
Issues on iOS 10.3.3 on iPad 4th Gen

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2609]
- [x] With the right conditions, embedded video player grows infinitely! #2632
- [x] Playthrough on item page advances correctly but does not start playback #2610 
- [x] Autoplay on playlists advances correctly but does not start playback for playlist items that have new sources (#2611 )
- [x] Lil' scrub appears but is missing duration and doesn't get updated while playing #2612
- [ ] Lil' Scrub is out of alignment. #2613 (iPad only)
- [x] Markers are not showing in the scrubber #2614 (iPad only)
- [ ] Quality switching appears to work but player has spinner until user clicks play #2615
- [ ] Double captions appear when captions are enabled in native player (fullscreen) and in MEJS4 player and viewing in non-fullscreen mode #2617
- [ ] Volume control does not appear (iOS, general) #2616
- [ ] Add new playlist modal not appearing
- [ ] Sometimes all markers appear at time 0 even if they are for a different time #2620

**Comment by davidschober** [comment]
Confirmed these.

**Comment by cjcolvar** [comment]
@davidschober Thanks for splitting these out! 

The first issue is with embedding a video player.  When I embedded in a wiki page I found that the embedded player's iframe grows infinitely tall when the player loads sometimes.  It would consistently happen for me with the first video when viewing this wiki page: https://wiki.dlib.indiana.edu/display/VarVideo/Embed+Test+Page
I was able to recreate it on a fresh wiki page with only one embedded video but only switching quality triggered the crazy growth.  More testing embedding outside of the wiki could be done to try to isolate the conditions that cause this odd behavior.
