### ISSUE TITLE
Import Timepoints From Ingested Media

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2772]
## Description

On ingest of media use a tool like jhove to read embedded technical metadata time points from source files if they exist and generate a template structure document. We will then save the structure to the work. Ideally we write code so that it's portable to 7. 

## Done looks like 
Target Wav files are chosen and structural metadata xml documents pre-generated from them at time of file ingest will be attached to master files.

## Tasks
- [ ] Find example wav files we are targeting 
- [ ] Determine 3rd party tool to use (jhove or something else)
- [ ] Write service wrapping 3rd party tool
- [ ] Call service with wav master file before processing
- [ ] Store generated structure document on master file

**Comment by davidschober** [comment]
@joncameron this was part of the structural metadata editor work, correct?

**Comment by joncameron** [comment]
One question: when would this run?

**Comment by joncameron** [comment]
#2964
