### ISSUE TITLE
Improve Page Load for Large Playlists

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2784]
### Description
Returning a playlist view page for playlists with a large number of playlist items takes a long time. 

### Done Looks Like
Playlists with large number of playlist items (75+) renders in less than 5 seconds.

### Example Item
- https://spruce.dlib.indiana.edu/playlists/208
   - This playlist item with 88 sections currently takes 9-10 seconds to render

### Tasks
Starting with prior work done on https://github.com/avalonmediasystem/avalon/tree/faster_playlist_load
- [ ] Figure out how to do cancancan checks on SpeedyAF objects (create new rules?, coerce objects into ActiveFedora::Base objects?, some other approach?)
- [ ] Profile again
- [ ] Make any additional changes
- [ ] Repeat until done looks like goal is met.

**Comment by bkeese** [comment]
Playlist item counts on MCO:
count : number of playlists
>200: 6 (only Chris's test playlist and clones)
>100: 11
>50: 35

**Comment by joncameron** [comment]
Taken care of with changes to how playlists are handled in 7.7.
