### ISSUE TITLE
Knowledge spike on JS state management libs and frameworks

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2786]
The swarm on modern JS practices (#2758) left us wanting to know more about JS state management libraries (redux, rxjs) and frameworks (react, vue, etc) to determine if either should be adopted for work on Avalon 7.  This is needed before we get into heavy UI customizations for the Avalon solution bundle.

### Done looks like
- rough consensus on path forward
- a document describing our approach to customization for the Avalon 7 solution bundle. 

#### Javascript state management packages
-  [x] #2791 - Investigate which state management packages can work directly with Javascript (not a framework).  Target RXJS first.
- [x]  #2791 - Generate a list of available packages with brief pros/cons to share with the team.  (this with the task above could be combined into a new issue)
- [x] #2793 - Install a state management package.
- [x] #2804 - Create a test page with the MEJS4 player playing a hardcoded media file, and test UI interactions (in the DOM, outside the player) with MEJS4.
