### ISSUE TITLE
Generate JS state application package decision document

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2791]
### Description
There is a need in Avalon 7 to incorporate a state management system package to handle front-end state interactions within the app and MediaelementJS.  To make the best decision, should do some a medium dive investigation listing 3 possible packages and their pros/cons to submit to POs and developers.

### Done Looks Like
- Research is done on top options for a state management system for Avalon 7.
- A single page document is generated detailing which packages we're considering, and pros/cons for each package.
- A decision is made from information in this document.

### Tasks
- [x] Investigate most popular state management packages (ones that will not fade away in 2 years)
- [x] Determine which can work with javascript directly, and not tied to a JS framework.
- [x] Generate a pros/cons document to share with the team.

References #2786

**Comment by adamjarling** [comment]
#### Redux
**Summary**
(from https://redux.js.org/)
- The whole state of your app is stored in an object tree inside a single store.
- The only way to change the state tree is to emit an action, an object describing what happened.
- To specify how the actions transform the state tree, you write pure reducers.

**ReactJS or vanilla JS?**
The most common use case appears to be using with ReactJS, as you can take advantage of the 'react-redux' library and middleware, but it seems Redux can also be used independently.  Here's a vanilla JS example implementation:

https://github.com/reactjs/redux/blob/master/examples/counter-vanilla/index.html

**Questions?**
How would this play with handling a massive amount of state events, such as Avalon consuming the MEJS 'timeupdate' continuous event, which drives much of the UI?   Would there be sluggish behavior, or would it be optimized?

#### RXJS
