### ISSUE TITLE
MediaelementJS Redux POC integration

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2794]
### Description
Configure and develop a POC test integration between Mediaelement player and Redux.

### Done Looks Like
- Avalon 7 plays a sample, hardcoded media file with MediaelementJS.
- Redux store variables are captured in the application, outside of MEJS.
- Redux store variables are captured from MEJS events.

### Tasks
- [x] Create a test page with the MEJS4 player playing a hardcoded media file.
- [ ] Test POC UI interactions (in the DOM, outside the player) to capture shared state.  See how it works.
- [ ] Test POC UI interactions (in the DOM, outside the player) with MEJS4.
- [ ] Test capturing MEJS events, and putting those events into the state management package...what this would look like, how it performs, etc.

References #2786

**Comment by davidschober** [comment]
child of #2865

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#96
