### ISSUE TITLE
Mediaelement Rails 5.1 webpacker configuration

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2804]
### Description
Research and implement best practice way to load JS dependencies with webpacker.  Using MediaelementJS (our player wrapper library), as an example, wire it up according to webpacker, Rails 5.1, patterns.   This may be different from the previous Rails asset pipeline pattern.

### Done Looks Like
- POC MediaelementJS player is loaded and initially wired up and plays a sample media file.

### Tasks
- [x] Research best way to import a library JS file in the Rails 5.1/webpacker environment.
- [x] Pull in MediaelementJS with `yarn`, so the lib files live in `node_modules`.
- [x] Implement a POC example of the MEJS play playing a test file with this new pattern.
