### ISSUE TITLE
Configure webpack build environment

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2806]
### Description
Configure our Rails webpack installation to include linting and quality control packages as part of the pipeline.   Write supporting documentation.

### Done Looks Like
- JS and possibly CSS (Sass) build tools are integrated into the webpacker pipeline.
- All libraries/packages are installed.
- Documentation is written.

### Tasks
- [x] Determine which build tools / packages to use, and install them.
- [x] Test everything works as expected.
- [x] Write documentation detailing the setup.

**Comment by adamjarling** [comment]
The following packages have been installed and configured:

- Prettier
- ESLint

Documentation generated (started) at:

https://github.com/avalonmediasystem/avalon-bundle/wiki/Front-End-Resources

**Comment by adamjarling** [comment]
Needs https://github.com/avalonmediasystem/avalon-bundle/pull/1 to go in first before pushing up the branch for a PR.
