### ISSUE TITLE
Set up Karma and Jasmine webpacker configuration

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2819]
### Description
Set up Karma Jasmine unit test configuration for our webpacker.

### Tasks
- [x] Install Karma and Jasmine `webpacker`'s way
- [x] Do Hello World from command line
- [x] Integrate into webpacker's compilation

**Comment by cjcolvar** [comment]
Is this ready to close?

**Comment by adamjarling** [comment]
Yep, closing now.
