### ISSUE TITLE
Implement IIIF Presentation 3.0 Spec Manifest Generation in iiif_manifest (First Pass)

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2850]
### Description
The iiif_manifest gem needs to be updated to serve Presentation 3.0 manifests that our media player can then consume.

### Tasks

- [x] Figure out code architecture for adding V3 alongside existing V2
- [x] Copy tests and modify for V3
- [x] Make tests pass
- [x] Add tests for labels
- [x] Add and test AnnotationPage
- [ ] Add and test choice for annotation body
- [ ] Add and test duration for canvas

### Done Looks Like

- pick a set of manifests we're scoped to (small set connect the story)
- iiif_manifest can generate a minimum viable Presentation 3.0 manifest according to what we need to drive our media player, based on the current status of the spec.

### Parent Issue
#2201

**Comment by davidschober** [comment]
@cjcolvar @bkeese has some prework to do... this is currently too big.

**Comment by mcwhitaker** [comment]
Chris has done the initial work.  Trey P was consulted about the approach and he approved. Brian and Ying were brought up to speed on it and new tickets are needed.

Need still to implement "choice".

**Comment by mcwhitaker** [comment]
@joncameron @davidschober  There are two tasks not completed here. Do we have a ticket to complete them? Or a note somewhere about our reasoning on this?

**Comment by joncameron** [comment]
I've created #2928 for the second pass, containing tasks that were outstanding from this issue.
