### ISSUE TITLE
Avalon MEJS player instantiated on work view for AV Works

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2853]
### Description
Displaying/injecting the Avalon player in generic work view.

### Done Looks Like
- For a standard work view on the generic work type, the Avalon player is displayed on the page.  No structural metadata displayed or interactions.  Keep this straightforward.

The following Hyrax partials need to be overwritten in Avalon Bundle:
`app/views/hyrax/base/_representative_media.html.erb`
`app/views/hyrax/file_sets/media_display/_video.html.erb`

### Tasks
- [x] BLOCKER: Pull in latest Hyrax 2.1
- [x] BLOCKER: Update docker config so a user can login and ingest an item.
- [x] Put hardcoded MEJS player into a generic work view first.
- [x] Play one file, which is specified from a mock IIIF manifest.

### Parent Issue
#2766

**Comment by adamjarling** [comment]
@joncameron Does this have to be the IIIF player, or the Avalon 6.3 player?   Should the player be hardcoded to play a test media file, or consume a media file the application ingested?

**Comment by joncameron** [comment]
@adamjarling I was thinking the Avalon IIIF player for the moment. It would be nice to have a hardcoded test file play back if possible, but it could also wait until #2854.

It would be good to talk this sprint about the Avalon IIIF Player, 6.3 player, and how we'll merge them as necessary.

**Comment by adamjarling** [comment]
@joncameron Got it.  I added some tasks above, and made references to 2 issues which need addressing before anything substantial can be done on this ticket.

**Comment by adamjarling** [comment]
@cjcolvar @joncameron I have a question on what this ticket will actually commit at current time.  Should I wait working on this item until I can ingest a video in my local Avalon Bundle?  Otherwise I'm just adding the code to Hyrax core page where it won't live, and probably not worth the commit?

**Comment by cjcolvar** [comment]
@adamjarling I think you can start adding this to `app/views/hyrax/file_sets/media_display/_video.html.erb` and `app/views/hyrax/file_sets/media_display/_audio.html.erb` copying from hyrax:
https://github.com/samvera/hyrax/blob/bfae31008c61715e98fd83a1ce13964c751c763c/app/views/hyrax/file_sets/media_display/_video.html.erb

Of course you won't be able to see any of that until you get a video file ingested so you may want to wait.

**Comment by adamjarling** [comment]
So as an update based on the slack comments, I pulled the latest master and re-started docker. 

I ran the following 2 commands:
```
rails hyrax:default_collection_types:create
bin/rails hyrax:default_admin_set:create
```
both of which failed with the following errors:
```
AARLING-MAC:avalon-bundle aja0137$ bundle exec rails hyrax:default_collection_types:create
rails aborted!
ActiveRecord::StatementInvalid: Could not find table 'hyrax_collection_types'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => hyrax:default_collection_types:create
(See full trace by running task with --trace)
AARLING-MAC:avalon-bundle aja0137$ bin/rails hyrax:default_admin_set:create
rails aborted!
Faraday::ConnectionFailed: Failed to open TCP connection to 127.0.0.1:8984 (Connection refused - connect(2) for "127.0.0.1" port 8984)
bin/rails:9:in `require'
bin/rails:9:in `<main>'

Caused by:
Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:8984 (Connection refused - connect(2) for "127.0.0.1" port 8984)
bin/rails:9:in `require'
bin/rails:9:in `<main>'

Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 8984
bin/rails:9:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => hyrax:default_admin_set:create
(See full trace by running task with --trace)
AARLING-MAC:avalon-bundle aja0137$ 
```

**Comment by adamjarling** [comment]
@cjcolvar @phuongdh I was still unable to create a "Collection" or "Work", but I was able to create a "Collection Type".  After creating this, I was able to create a "Collection", then able to "Add a new work to collection".  The work add seemed to work, but adding a video file does not save the file.

Does it matter I ran the 2 commands above after `archivist1@example.com` was already created?   Is there a way to delete my account, or remove `archivist1@example.com`?
