### ISSUE TITLE
Add Webpacker support for Sass files

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2863]
### Description
In Webpacker's "packs" pattern within the Rails app, it's encouraged to group CSS/Sass/styles within their own modules living in `app/javascript/packs`.  So this would be a good place for example to place Mediaelement specific custom styles so they're abstracted from the rest of the application that doesn't care about Mediaelement UI elements.

This ticket should add support for Sass files, beyond already supported CSS.

### Done Looks Like
- Custom `.scss` files are processed and applied as expected.

### Tasks
- [ ] Configure support for `.scss` files in webpacker.
- [ ] Determine best pattern for applying.
- [ ] Write documentation in the Wiki for other devs to follow the pattern.

**Comment by adamjarling** [comment]
I'm blocked on this until I can get my avalon-bundle docker container to load properly.  It takes hours and just stalls out now.  Maybe @phuongdh can help me when we re-group?
