### ISSUE TITLE
6.4 Public Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2868]
### Description
Releasing 6.4 to the world.

### Tasks
- [x] Write a draft of release notes on Github
- [x] Publish release on Github https://github.com/avalonmediasystem/avalon/releases
- [x] Update wiki with release notes as needed
- [x] Publish blog post announcing the release
- [x] Update front page of website with 6.4 announcement and any other website pages with references to 6.4
- [x] Put announcement on Twitter and Facebook
- [x] Send out email to Samvera community mailing list
- [x] Publicize in appropriate Slack channels
