### ISSUE TITLE
6.4 Code Freeze and Merge

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2870]
### Description
Code merges, update and cleanup for the release of 6.4.

### Tasks

- [x] Update version in code
- [x] Update license headers in files
- [x] Tag dependency repos
- [x] Update gemfile to point to those tags
- [x] Merge to staging branch
- [x] Staging pushed to Mallorn for testing
- [x] Configure intercom on Mallorn

#### Post Testing
- [ ] Merge staging into master
- [ ] Hit the release button in Github
- [ ] Create tag for v6.4.0 (should already happen with hitting release button)
