### ISSUE TITLE
6.4 Documentation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2871]
### Tasks
- [ ] Upgrade Instructions (https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.3+to+Avalon+6.4)
- [x] Update Known Issues
   - [x] https://github.com/avalonmediasystem/avalon/issues/2883
- [x] Write documentation regarding dynamic adaptive streaming
- [x] Update version numbers on Wiki to refer to 6.4

**Comment by joncameron** [comment]
Intercom documentation will be a separate issue.

**Comment by bkeese** [comment]
I added intercom.yml to configuration files wiki page.

**Comment by mcwhitaker** [comment]
@mschnaars will update end user documentation.
