### ISSUE TITLE
Create Design Documents for Structural Metadata Editor

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2949]
### Description
We need to identify the scope, priorities, and necessary work for Structural metadata editor, to be able to start work and guesstimate it's size.  A good starting point may be to create a wireframe of what the 'new' UI would look like, what the user expects, then component by component work through the UI and identify how, what, and can be done.   Assuming this new work is considered an improvement over what's currently existing, then we can create issues from the wireframe pieces.

#### Mockups
https://ninjamock.com/s/MBVKMRx

### Done Looks Like
- Wireframe created and components are generally described/understood.
- Generating a clickable waveform element is fully described and UI interaction expectations are defined.
- An existing clickable waveform element (Wave Surfer) has been evaluated and tested briefly.
- We've determined whether an existing waveform representation tool (Wave Surfer or another alternative), meets our needs.
- We've determined whether we're using a visual waveform element or not.
- Deliverable: Refined scope of what the application module would look like.

### Tasks
- [x] Create wireframe and components are generally described/understood.
- [ ] Fully describe clickable waveform element's UI interaction expectations.
- [ ] Play around with an existing clickable waveform element (Wave Surfer).  See what it can do.
- [ ] Determine whether an existing waveform representation tool (Wave Surfer or another alternative), meets our needs.
- [ ] Determine whether we're using a visual waveform element or not.
- [ ] If we're not using a visual waveform editor, discuss how new work would be better than what's existing.

Child of https://github.com/samvera-labs/avalon-bundle/issues/177

**Comment by adamjarling** [comment]
UI Sandbox repo:
https://github.com/avalonmediasystem/structured-metadata-editor-sandbox

UI Sandbox repo GitHub hosted site:
https://avalonmediasystem.github.io/structured-metadata-editor-sandbox/

**Comment by mcwhitaker** [comment]
Parts of this work were moved to #3020
