### ISSUE TITLE
Structural Metadata Editor - UI Discussion

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2951]
_From @davidschober on April 26, 2018 16:38_

---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1931
Originally created by @davidschober on *Wed, 17 May 2017 15:11:21 GMT*

---
## Description

We need to make a decision about how structural metadata will be edited within a hyrax-driven environment. Currently our structural metadata editor is a quick and dirty xml editor. The schema currently: https://github.com/avalonmediasystem/avalon/blob/dd9ea47de0fb4cc3bc2503b0b414e98fd2ea48ae/public/avalon_structure.xsd

An ideal solution would be to have editable fields associated parent and children which have a label and time extent so that an end user  can add a parent and the children and never have to touch the xml.

## Done looks like 

- Path forward is determined
- sketches are made of interface, ideally using a "hyrax-y" way of doing it
- if we punt on a visual, point and click editor, a clear path to that end is documented
- A review of hyrax design patterns if necessary
- break out technical stories as necessary.

## Tasks

- [ ] Review current graphical interface in Avalon
- [ ] Review current Hyrax interface and consider what a Hyrax style editor would look like
- [ ] developers review Hyrax UI patterns
- [ ] wireframes generated

_Copied from original issue: samvera-labs/avalon-bundle#103_

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1931#issuecomment-302124680
Originally created by @bkeese on *Wed, 17 May 2017 15:20:37 GMT*

---
Our current editor does have a graphical interface option that sounds like what is described here. It's a bit clunky though and might only serve as an example of what we want and don't want. To see it, just click the "Graphical" button within the editor.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1931#issuecomment-303412778
Originally created by @carrickr on *Tue, 23 May 2017 14:17:56 GMT*

---
I did task this out, but honestly it seems like we could split this into multiple tickets.  This could remain as the parent perhaps.

- One for a group of people to review the current editor and current Hyrax fielded data editors (that might inform the design for ours)
- one for developers to review UI design patterns
- one for designers to generate wireframes

This also feels a bit small at 3 considering the number of people impacted by the design.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1931#issuecomment-307418224
Originally created by @jwd on *Fri, 09 Jun 2017 15:20:26 GMT*

---
I strongly believe that what we ultimately need here is an interactive playlist editor that works with the player so that time points can be pulled in from current scrubber location, allowing the user to scrub around to find timepoints from which to construct structural metadata elements.

**Comment by davidschober** [comment]
Met with PIs and got approval for the following wireframes. We can walk you through the interactive versions in advance of #2949 
![audio player](https://user-images.githubusercontent.com/4803230/39839587-26e14fa0-53a2-11e8-904b-644c70a64686.png)
![new heading](https://user-images.githubusercontent.com/4803230/39839588-26f14c52-53a2-11e8-8bc9-5791be4cf39f.png)
![new time sequence](https://user-images.githubusercontent.com/4803230/39839589-270580d2-53a2-11e8-8088-78c3118fbb51.png)

**Comment by davidschober** [comment]
ping @adamjarling @bkeese @cjcolvar

**Comment by adamjarling** [comment]
Looks good.  Does this assume time syncing between Mediaelement player and the secondary waveform 'player'?

**Comment by mcwhitaker** [comment]
@adamjarling Is syncing difficult? If not, the ideal is perfect syncing. 

If syncing is difficult, I can see the need for perfect syncing while playing not so important if we read the time from MediaElement when creating a span -- this will serve the use case of someone listening to the piece to determine where to set the time points. However, clicking on the waveform will definitely need to get MediaElement synced with it. The idea is that, instead of listening to the whole piece, someone can look at the waveform to go to the time point they wish to use for a new span. 

My two cents...  the decision is with the POs (who should consult with our users, I think, before deciding that perfect syncing is not important).

**Comment by mcwhitaker** [comment]
![image](https://user-images.githubusercontent.com/16720883/39876724-eef98cc4-5441-11e8-8e3b-73f687755411.png)

**Comment by davidschober** [comment]
![new heading](https://user-images.githubusercontent.com/4803230/39881398-6f43cf9e-5446-11e8-9ccb-bc8b32fdf028.png)
![new time sequence](https://user-images.githubusercontent.com/4803230/39881399-6f500dae-5446-11e8-9b35-e5901b4599f2.png)
![audio player](https://user-images.githubusercontent.com/4803230/39881400-6f632a10-5446-11e8-9669-b5b502eb1b28.png)

**Comment by davidschober** [comment]
## Structural Metadata editor interface
Assumptions:

- this is a basic structural editor, advanced work can be done by using the xml editor (advanced editor)
- children show up in order based on start times
- headers (parents) show up in order based on the start time of the children

## Basic interface

- Waveform is zoomable and syncs with playhead. 
- buttons for adding headers or time span
- edit buttons for time sequence or header
- add child  -- a shortcut for adding a child to a parent element
- add parent  -- a shortcut for adding a parent to a child element
- delete -- makes it like it never happened

![audio player](https://user-images.githubusercontent.com/4803230/39881507-c0f555f6-5446-11e8-8648-26118b64f274.png)

## Add a Header

- dropdown for adding a header under a parent
- title of parent

![new heading](https://user-images.githubusercontent.com/4803230/39881505-c0ddb36a-5446-11e8-9f89-5d28cf2583ed.png)

## Add a child

- highlight with grab handles on waveform updates start and end times
- "child of" dropdown for nesting
- title of element
- start and stop text fields can be updated textually which will be reflected in the highlight. 

![new time sequence](https://user-images.githubusercontent.com/4803230/39881506-c0ea5232-5446-11e8-90b1-11184a28f3b1.png)
