### ISSUE TITLE
(SME) - Create localStorage JSON solution structure

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3010]
### Description
Configure a good way to represent structured metadata hierarchy as a JSON object which drive the UI and also can eventually be converted to XML format the server needs upon form submit.

### Done Looks Like
- Structured metadata entries are represented by JSON saved temporarily in localStorage (browser).  This structure also makes sense when mapped against existing XML data structure.

### Tasks
- [x] Work through JSON structure
- [x] Get approval from other devs that it makes sense.
- [x] Implement in localStorage in code.

Child of samvera-labs/avalon-bundle#177

**Comment by adamjarling** [comment]
Need some identifying "id" or something in the JSON.  Does this exist in data passed down from the server by chance?  Pinged @cjcolvar about getting a mock data structure for what is currently passed down...and will continue on this.

**Comment by adamjarling** [comment]
Running with a JSON structure which resembles the current XML data.

```
[
  {
    "type": "div",
    "label":
      "Faculty/Student Recital",
    "items": [
      {
        "type": "span",
        "label": "[ambience]",
        "begin": "00:00:00.00",
        "end": "00:00:23.60"
      },
      {
        "type": "span",
        "label": "[announcement]",
        "begin": "00:00:23.60",
        "end": "00:03:02.11"
      },
      {
        "type": "div",
        "label": "Richard Wagner, Der fliegende Holl&#xE4;nder (excerpts)",
        "items": [
          {
            "type": "div",
            "label": "Sub-heading Label",
            "items": [
              {
                "type": "span",
                "label": "&quot;Die Frist ist um&quot;",
                "begin": "00:03:02.11",
                "end": "00:13:48.00"
              },
              {
                "type": "span",
                "label": "&quot;Weit komm ich her&quot;",
                "begin": "00:13:48.00",
                "end": "00:28:03.24"
              }
            ]
          }
        ]
      },
      {
        "type": "div",
        "label": "Giuseppe Verdi",
        "items": [
          {
            "type": "span",
            "label": "Simone Boccanegra (1881 version): &quot;Il lacerato spirito&quot;",
            "begin": "00:28:03.24",
            "end": "00:33:10.94"
          },
          {
            "type": "span",
            "label": "I vespri siciliani: &quot;Merc&#xE8;, dilette amiche&quot;",
            "begin": "00:33:10.94",
            "end": "00:37:31.09"
          }
        ]
      },
      {
        "type": "div",
        "label": "Richard Strauss, Ariadne auf Naxos (excerpts)",
        "items": [
          {
            "type": "span",
            "label": "&quot;Lieben, Hassen, Hoffen, Zagen&quot;",
            "begin": "00:37:31.09",
            "end": "00:39:35.59"
          },
          {
            "type": "span",
            "label": "&quot;Es gibt ein Reich&quot;",
            "begin": "00:39:35.59",
            "end": "00:46:40.59"
          }
        ]
      },
      {
        "type": "span",
        "label": "Gaetano Donizetti, Lucia di Lammermoor: &quot;Tombe degli avi miei&quot;",
        "begin": "00:46:40.59",
        "end": "00:52:37.25"
      }
    ]
  }
]
```
