### ISSUE TITLE
(SME) - Wire up SME forms to display to UI

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3011]
### Description
Wire up the forms for "New heading" and "New time span" so they populate the UI when submitted.

### Done Looks Like
- Form submissions work and update the UI.

### Tasks
- [x] Handle form displaying event, and form submission event for "New heading".
- [x] Handle form displaying event, and form submission event for "New time span".
- [x] Update the redux store
- [x] Use redux store JSON object to create new UI.

Child of samvera-labs/avalon-bundle#177

**Comment by adamjarling** [comment]
@joncameron @davidschober This work will now be done as part of the React SME app, so pulling into "In Progress".
