### ISSUE TITLE
(SME) - Bring in waveform UI through peakjs

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3012]
### Description
Bring in one of the waveform display options into the sample application

### Done Looks Like
- Live waveform representation is in the UI.  Can be zoomed, expanded, etc... 
- Just initial implementation

### Tasks
- [x] Get recommended tool from other devs.
- [x] Bring in library.
- [x] Bring in sample data and/or object which generates the waveform in UI.

Child of samvera-labs/avalon-bundle#231
