### ISSUE TITLE
(SME) - Convert JSON to XML on form submit

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3014]
### Description
Prep data from `localStorage` JSON file into a serialized format the server side expects.

Is this XML?

### Done Looks Like
- On final form submit, the newly created / edited structural metadata changes are successfully saved to the server.

### Tasks
- [ ] Determine what the current serialized data looks like when sending to server.
- [ ] Should this be the same, considering we're re-working this feature?
- [ ] Get a sample data structure/format for what the server needs
- [ ] Write a parsing function(s) which prep the data in required format.

Child of samvera-labs/avalon-bundle#231

**Comment by joncameron** [comment]
An example XML file should be attached to this issue to check against.

**Comment by davidschober** [comment]
We decided this would be server side.
