### ISSUE TITLE
Create parity between structured-metadata-editor-sandbox and the new React SME repo app

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3054]
### Description
Need to build up the new React SME app to look, function and feel like: 

https://avalonmediasystem.github.io/structured-metadata-editor-sandbox/

### Done Looks Like
- Feature parity between new React SME app and existing vanilla sandbox SME app.

### Tasks
- [x] Import required libs (Bootstrap, Lodash, etc.)
- [x] Create components for displaying UI.
- [x] Create components for form inputs.

needs #3011
