### ISSUE TITLE
(SME) - Handle editing of Timespan in the UI

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3071]
### Description
Handle editing of timespan in the UI.

### Done Looks Like
- Can add a new timespan
- Can edit existing timespan
- Can delete a timespan
- On all these actions the UI tree responds accordingly.

### Tasks
- [x] Add a new timespan
- [ ] Edit existing timespan
- [x] Delete a timespan
- [x] On all these actions the UI tree responds accordingly.

 child of https://github.com/samvera-labs/avalon-bundle/issues/231
