### ISSUE TITLE
(SME) - Handle positioning of Timespan parent edit in the UI

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3072]
### Description
When a new parent is selected for an existing Timespan, we need to validate that the movement is valid in relation to the time span start and end times.

### Done Looks Like
- Validation is in place to confirm an attempted re-positioning of timespan is legal. (handle through visual 'drop targets' of where the timespan can legally be dragged).
- Edited timespan,  if invalid, displays an error message to user.  (When editing the begin and end times)
- Edited timespan, if valid, moves to appropriate spot in the UI. (Need to think about how to handle the parent here...)

### Tasks
- [x] Put validation is in place to confirm an attempted re-positioning of timespan is legal.
- [x] If edited timespan is invalid, display an error message to user.
- [x] If edited timespan is valid, moves to appropriate spot in the UI.

child of https://github.com/samvera-labs/avalon-bundle/issues/231

**Comment by adamjarling** [comment]
This ticket's original scope will change as a result of the drag n drop introduced in #3098.  I think for editing a Timespan, it might be easier to just edit the actual times and label, but instead of selecting a parent from the dropdown menu in the edit screen (similar to adding a Timespan), that's where the drag and drop will come into play.  

So the standard edit form would just let the user edit:
- Label
- Begin time
- End time

Then through some type of user interaction (in place, POC in #3098), this is how to move the Timespan within the structure.

**Comment by adamjarling** [comment]
The trick will be, how to handle a begin time edit, if it changes the position of the timespan in relation to other timespans.  How will the header be determined if there are multiple options?   

I think we just default to the most simple header option on a begin time edit, and then the user can further refine through dragging if need be?

**Comment by Dananji** [comment]
When adding/editing a timespan to/from end of the structure, the header selection list does not give the option of choosing the last childless header. For an example: for a structure as below, if you try to add a timespan with begintime > 00:09:03.23 the header list will only show the option of 'First segment'. 'Second segment' is not regarded in the valid heading construction.

![Screenshot from 2019-01-23 11-20-34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c0e783fd9fd29001136b2d2/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f37a3dd7b068ee1336535f424da853444d04bea6d37ef5f22e7a98590ce9876c5d27cf6942aaea831dbf06ba248e1ed3b1bc8c5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cfe49e74d51a0143666ef647b.png)

And when drag & drop function is invoked, option of dragging it to the last childless header is not presented.

![Screenshot from 2019-01-23 11-24-13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c0e783fd9fd29001136b2d2/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f37a3dd7b068ee1336535b424faf53444d04bea6d37ef5f22e7a98590ce9876c5d27cf6942aaea831dbf06ba248e1ed3b1bc8c5edcfa7f74b9dfd0126754505a9bf54f34a9934acd5cfe49e74d5ca3153460e5647b.png)

It seems the program does not allow the user to add any timespans to the last heading if it's childless.

**Comment by adamjarling** [comment]
Ah, yes this needs to get fixed.  Feel like taking a crack at it?

**Comment by Dananji** [comment]
Yes, sure!
