### ISSUE TITLE
(SME) - Handle positioning of Heading parent edit in the UI

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3073]
### Description
When a new parent is selected for an existing Heading, we need to validate that the movement is valid in relation to the UI.  We also need to handle what to do with children of the edited Heading.

### Done Looks Like
- Validation is in place to confirm an attempted re-positioning of Heading is legal.
- Edited Heading,  if invalid, displays an error message to user.
- Edited Heading, if valid, moves to appropriate spot in the UI.
- Children time spans of Heading behave in an expected way (clarify this?), when a Heading is moved.

### Tasks
- [ ] Put validation is in place to confirm an attempted re-positioning of Heading is legal.
- [ ] If edited Heading is invalid, display an error message to user.
- [ ] If edited Heading is valid, moves to appropriate spot in the UI.
- [ ] If edited Heading is valid, handle children items in an appropriate way.
