### ISSUE TITLE
Peaks.js Displays Masterfile Waveform

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3126]
### Description
When the react component is loaded in the structural metadata editor, it requests the peaks JSON from the endpoint. The structure JSON from the other endpoint. Have to load up from that. There's going to have to be a save that posts it back to that structure endpoint.

Waveform JSON endpoint:
/master_files/:id/waveform.json

### Tasks
- [ ] Request peaks JSON from waveform JSON endpoint
- [ ] Request structure JSON from structure endpoint
- [ ] Save structure back to endpoint
child of https://github.com/samvera-labs/avalon-bundle/issues/231

**Comment by mcwhitaker** [comment]
Abandon in favor of #3134 and #3133.
