### ISSUE TITLE
(SME) Refactor modal editing of items, to inline editing

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3155]
### Description
We need to move away from modals when handling future integration of this app into Avalon 6 and 7.  Assuming it's possible (reference issue here), refactor the modal code to be inline editing for each list item.

### Done Looks Like
- When editing a timespan or heading, an inline form appears.
- Modals are no longer used in editing.

### Tasks
- [ ] Implement/create/refactor list item component(s) which has an 'edit' state, and which display inline, editable form elements.
- [ ] Move current modal logic / pieces to the inline form elements.
- [ ] Eliminate modals for editing.

**Comment by adamjarling** [comment]
@Dananji Feel free to run with this a little bit when you're done with the Jest testing.  Based off my starter branch for the inline stuff.

**Comment by Dananji** [comment]
Yes sure.
