### ISSUE TITLE
(SME) Refactor add items, removing modals, and use slide down type panels

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3156]
### Description
Currently adding a new timespan or heading is handled via modal windows.  We need to remove modals for integration plans.  Use some type of slide down feature which displays the add forms.

<img width="796" alt="add-buttons" src="https://user-images.githubusercontent.com/3020266/51629682-d8921900-1f0d-11e9-9201-3fbb5bd6355a.png">

### Done Looks Like
- Modals are no longer used when adding a new timespan or heading.
- The add forms slide down, then slide back up when submitted or canceled.

### Tasks
- [x] Create slide down panel functionality.  
- [x] Either use a React Bootstrap component, or just a plan `div` and leverage React transitions to show/hide the panel and mimic show/hide behavior.
- [x] Remove modal dependency for this action.
- [x] Ensure that the two slide panels and forms (one for a timespan, one for a heading) operate in tandem with each other.  Basically only one should show at a time.  And they should react to submitting / canceling behavior.

depends on #3153 
child of https://github.com/samvera-labs/avalon-bundle/issues/231
