### ISSUE TITLE
Edit Span Timepoints Using Waveform Viewer

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3164]
### Description
Within the structural metadata editor, users can change the timepoints of a defined range within the waveform by clicking and dragging handles on either side of the range.

### Done Looks Like
- A segment which is in an edit state (user clicks the edit icon) becomes editable: handles appear on the beginning and end of the range, allowing users to click and drag to change the time value for the beginning or end of the range, based on which handle they're using.

### Tasks
- When a timespan is created,
    - [x] Add the segment to the waveform with the respective color after the timespan is saved and re-render the UI.
- When edit on a timespan is clicked,
    - [x] Change the color of the active segment(span) in waveform
    - [x] Show the handles on either side of the segment
    - [ ] Retrieve the time the handles point in the waveform
- When save/cancel on timespan edit form is clicked,
    - [x] Revert the color of the segment in waveform
    - [x] Remove handles on either side of the segment in waveform
- When a timespan is deleted,
    - [x] Delete the segment from waveform and re-render the waveform in UI
- [x] Only one segment will be editable at a time
- [ ] Write tests to logic functions

### Notes
- When a range is editable, the segment in peak.js should change color to indicate that it is currently in an edit state
   - Color of the segment should be #FBB040

#### A user decides to edit the second segment (span). Before editing, the users sees the waveform below.
![screen shot 2019-01-31 at 9 46 57 am](https://user-images.githubusercontent.com/1406618/52062049-c5023600-253d-11e9-9d03-fbcd0d609eb7.png)

#### The user takes the edit action and now sees what is shown below. The segment in peak.js is changed to _editable_. The range changes color and a handle appears, allowing the user to click and drag.
![screen shot 2019-01-31 at 9 46 35 am](https://user-images.githubusercontent.com/1406618/52062055-c895bd00-253d-11e9-89bc-0071374cedca.png)
(The handle is a bit hard to see in the preview in Github, but it's there)

child of https://github.com/samvera-labs/avalon-bundle/issues/231

**Comment by joncameron** [comment]
Note: specify color in CSS rather than as attribute on JSON?

**Comment by Dananji** [comment]
Note: Since one segment will be editable at a time, we will always have one edit form (corresponding to the segment editable) open at a time.

**Comment by Dananji** [comment]
Time changed in the waveform segment shows up in the structure after saving not while dragging the handles in the waveform.

**Comment by Dananji** [comment]
Waveform logic tests were written for couple of functions
