### ISSUE TITLE
Bring Structural Metadata Editor into Avalon

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3223]
### Description
Figure out the best way to bring the structural metadata editor into the Avalon 6 environment.

### Done Looks Like
- Decision made about delivering the structural metadata editor within Avalon 6
- This work undertaken and the editor can be launched in the Avalon 6 context

### To Do
- [x] Investigate whether `nbw` is still best way to turn a `create-react-app` project into a npm package (#3241).
- [x] POC work for packaging up SME application, using a given strategy/tool (#3242).
- [x] Test importing of npm package from a Github branch (so we don't have to officially publish to npm yet) (create issue).

### Note
Adam noted that ideally this would be through a single module import.

**Comment by joncameron** [comment]
Adam will detail out todos and steps needed in this ticket.

**Comment by adamjarling** [comment]
Some beginning documentation created below:

@joncameron @cjcolvar @Dananji 

https://github.com/avalonmediasystem/structured-metadata-editor-react/wiki/Packaging-the-module-for-export

https://github.com/avalonmediasystem/react-structural-metadata-editor
This is incomplete, but to test this, next week or what not here are the main steps:

1. Follow the instructions to package the files in the `structured-metadata-editor-react` repo.
2. In `react-structural-metadata-editor` `/src` folder, delete everything, except `index.js` file (which is the unique entrance file for the packaging we want static here).
3. Manually copy over the files in the the `/src` directory.
4. Continue with packaging instructions on the README.

**Comment by joncameron** [comment]
@adamjarling Should I create a new ticket for future work on packaging? Based on the instructions and things across the two separate repos it sounds like something more elegant is in the works eventually but I don't think we have an issue about that yet.
