### ISSUE TITLE
POC work for packaging up SME application, using a given strategy/tool

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3242]
### Description
After a decision is made on which tool/environment to package up the SME app, begin work on packaging it.   Or try packaging it with 2 alternative tools and evaluate which is best?

### Done Looks Like
- A POC exportable NPM package is created from the Structural Metadata application.

### Tasks
- [x] Create a packaging repository `react-structural-metadata-editor`
- [x] Create a new `nwb` project to be the packager repo.
- [x] Re-structure `structured-metadata-editor-react` application so it sets itself up easily to drop all files in `/src` directly into the packaging application.
- [x] Copy all files over to `react-structural-metadata-editor` and get it to build successfully.
- [ ] Thin out any unnecessary code from `react-structural-metadata-editor` application.
- [x] Write documentation (see below)

child of #3223

**Comment by adamjarling** [comment]
@Dananji @cjcolvar I have 2 working scenarios at the moment, where I can create a bundled SME application ready to export (haven’t tested importing it quite yet).   

### Scenario 1
One scenario is where code is picked up out of the development application, and placed into an `nwb` application, which handles the packaging for NPM.

#### Advantages
- Can keep all development build configuration simple, and the responsibility of `react-scripts` via `create-react-app`.  No need to mess with `webpack`, or updating under the hood dependencies.
- `nwb` tool handles the packaging.  It's officially recommended as the packaging solution in `create-react-app` docs.

#### Disadvantages
- Need to maintain two separate repositories.  One for development, one for packaging.
- May need to find an automated dev ops solution to manually moving the correct files from dev repository to packaging repository.

### Scenario 2
The second scenario is to handle the packaging from the existing development application.  I have it in a place now, where everything is more or less playing nice with each other and it works.

##### Advantages
- Only one repository to maintain.
- Create a new npm command to handle the publishing of repository.
- We can highly customize the build process.

#### Disadvantages
- Ejecting from our `create-react-app` application introduces a very advanced, complex `webpack` configuration.  This must be maintained.  Learning curve?
- All dependencies must be manually maintained and updated.  There's a lot of devDependencies CRA ejects.  
- We can highly customize the build process.  
- It's finicky with managing interdependency versions to get everything in sync.


Still moving forward, just wanted to get this out of my head given where I'm currently at.

**Comment by adamjarling** [comment]
@cjcolvar @Dananji  What are your thoughts on including Bootstrap css as a dependency of this module?  I think it's going to fight with Avalon implementations of Bootstrap css... but

The tricky part is that we've built this app based on a Bootstrap dependency to maintain the look & feel.   We're using `react-bootstrap` as a dependency to get access to Bootstrap React components.   `react-bootstrap` does not have a Bootstrap CSS dependency; it requires its application to pull it in separately.  

So locally to display the UI we need a Bootstrap CSS dependency.  To develop against.

I think I just answered my own question.  I think we assume a consuming application will already have Bootstrap `v3.x` available.   This means that a local build of the demo will have to pull in Bootstrap on its own... ok sorry thinking as I type here.  

This sound ok?

**Comment by Dananji** [comment]
@adamjarling I did not understand the last part. But from the rest what I understood was that, you are suggesting we do not add Bootstrap CSS as a dependency of this module, and assume the parent application comes with Bootstrap the SME module can consume?

If it works, then I'm good with that :+1:
