### ISSUE TITLE
React IIIF Media Player move components and app into the new repo environment

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3426]
### Description
For consistency, we should move the React IIIF Media player components / app into the same packaging environment we're using for the Structural Metadata editor.

### Done Looks Like
- React IIIF Media Player runs a local dev environment, and packages it's contents the same way as the Structural Metadata Editor.

### Tasks
- [x] create a new branch, remove the `nwb` package.
- [x] Update `package.json` file to reflect new dependencies.
- [ ] Make sure components wire up to the new environment ok.

**Comment by adamjarling** [comment]
@bkeese @mcwhitaker @Dananji In re-working this package, I'm getting a network error on the following manifest url, used previously:

https://mallorn.dlib.indiana.edu/lunchroom_manners.manifest.json

Is there an updated URL the player should be using for testing?

**Comment by davidschober** [comment]
Should we be using Mallory manifests from a live object? 

https://mallorn.dlib.indiana.edu/media_objects/pg15bd93n/manifest.json
https://mallorn.dlib.indiana.edu/media_objects/cz30ps74m/manifest.json <https://mallorn.dlib.indiana.edu/media_objects/cz30ps74m/manifest.json>

**Comment by bkeese** [comment]
We must have forgotten to copy this file over to the new deploy when we released recently.

When I get back from lunch, I'll do it.

-Brian


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by mcwhitaker** [comment]
@adamjarling I think David is correct and we should be using a live manifest to ensure we are using the latest in terms of iiif spec.

**Comment by adamjarling** [comment]
Will do.  I'll plug a live manifest into the module, and make it configurable so any consuming application can deliver a `prop` IIIF manifest string value to the player React component.
