### ISSUE TITLE
Sass styles cleanup and continue modularizing into logical groupings

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3600]
### Description
In the UI cleanup work, there are most likely a decent amount of now unused styles defined in `app/assets/stylesheets/avalon.scss`.  To avoid confusion and optimize bundle size, these should be eliminated.

### Done Looks Like
-  All unused style definitions in `.scss` files are removed.
- All style definitions live in their own logical groupings, separated by files. (ie. all `header` styles live in `app/assets/stylesheets/avalon/_header.scss`

### Tasks
- [ ] Use a tool to identify unused CSS style definitions?   Worse case scenario application wide search...
- [ ] Remove unused style definitions
- [ ] Modularize all reasonable style definition candidates in `app/assets/stylesheets/avalon.scss` to their own Sass module files.
