### ISSUE TITLE
Implement new homepage design

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3636]
### Description
We have a new homepage design intended for Avalon on Hyrax, however we could try to implement the design now.  Updating the homepage might give a nice bow on top of recent UI work.

![avalon-homepage-draft-1](https://user-images.githubusercontent.com/3020266/65781857-0de0ad80-e112-11e9-8033-c25d686779cd.png)

### Done Looks Like
- New homepage implemented

### Tasks
- [x] Work on the HTML markup in the views
- [x] Wire up the data to the views (or at least make sure the the view has all the data it needs to make the new design work).
- [x] Consider using any React components?   Would it be easier, or any benefit?

**Comment by davidschober** [comment]
Cool. Let's attack this after SC.

**Comment by adamjarling** [comment]
@davidschober @joncameron Any interest in getting this into the 7 release?

**Comment by mcwhitaker** [comment]
@adamjarling In theory, we are supposed to be feature-complete by the end of next week. Would changing this require time from anyone at IU? If so, I don't think we can manage it.

**Comment by adamjarling** [comment]
@mcwhitaker Ah, understood.  Well, the dynamic content would be the featured collection part.  If the code is not in place to support that on the back-end, then this would require some IU dev time I'm guessing?  @cjcolvar ?   It would be a nice bow on the 7 release if possible to squeeze it in...but don't want to rush anything.

**Comment by cjcolvar** [comment]
I think it might already be done since the collection listing page consumes a json endpoint which should have the same data as would be displayed on the homepage.
https://spruce.dlib.indiana.edu/collections.json

**Comment by cjcolvar** [comment]
I guess the only new part would be "featured"-ness.  How does a collection become "featured" and returning that information in the json endpoint.  Probably would be fairly easy but would a little UX thought.

**Comment by joncameron** [comment]
I'm definitely interested but my concern would be time. Seems like a good backlog buddies discussion.

**Comment by adamjarling** [comment]
Here's where the current UI dev stands visually.  Branch pushed: `3636-new-homepage-design`

![image](https://user-images.githubusercontent.com/3020266/69259843-81d48a80-0b84-11ea-8c95-82daceeaebd9.png)
