### ISSUE TITLE
Investigative work for IIIF-Player component implementation  

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#4257]
### Description
Investigate how features and functionality in the iiif-player React component can be implemented.

### Tasks
- [x] Explore how the React components for playlists and the normal media player will be implemented (e.g. different features in the 2 scenarios) 
- [x] How the React component interacts with the other non-React components in the page once brought into Avalon
- [x] Passing changes made in React component to the back-end (end-points are present in the ruby code)

**Comment by Dananji** [comment]
End points:
- add to playlists
- create thumbnail - CORS issues when trying to access from localhost
- add/edit markers in playlists - authenticity token required when component is inside avalon
