### ISSUE TITLE
Avalon 7.3 Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4559]
# Release Checklist

#### Code Changes
- [x] Dependency Check #4531
- [x] Troubleshoot/fix error in streaming server check on About page #4555
- [x] Fix CircleCI issues #4556
- [x] Make some updates to components to stop some "obsolete" warnings we are getting with Ruby 2.7 #4549
- [x] Update code files with version number
- [x] Update license headers in files if needed (https://github.com/avalonmediasystem/avalon/pull/4584)
- [x] Docker cleanup #4615 
- [x] Merge `develop` into `staging` @apertome 
- [x] #4624 
- [x] Tag dependency repos
- [x] Update gemfile to point to those tags
- [x] Merge staging into master

#### Docker-specific
- [x] Clean up Dockerfile -- there is some old stuff left there and some debug output we need to get rid of
- [x] Make sure the correct tools are being installed (binaries like ffmpeg, mediainfo, yarn) - #4550
- [x] #4628

#### Application Testing
- [x] Full Application Testing @joncameron 

#### Documentation
- [x] Update Known Issues documentation page
- [x] Update current version number on the documentation wiki

#### Marketing and Outreach
- [x] Write a draft of release notes on Github
- [x] Publish release button in Github
- [x] Create tag for v7.3 (should already happen when pressing release button in above step)
- [x] Publish release on Github https://github.com/avalonmediasystem/avalon/releases
- [x] Update avalon-docker to point at new release docker tag and github tag
- [x] Update wiki with release notes
- [x] Publish blog post announcing the release
- [x] Update homepage with blog post for release announcement
- [x] Update homepage with the updated version and documentation links
- [x] Put announcement on Twitter
- [x] Put announcement on Facebook
- [x] Send out email to Samvera community mailing list
- [x] Publicize in appropriate Slack channels

**Comment by apertome** [comment]
At this point, after more testing, I'm satisfied that the encoding issues I was concerned about are only showing up in dev environments with minio. Unless there are other concerns, I think we're good to do the release.
