### ISSUE TITLE
Demo Environment for Avalon Tracking Development

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4833]
# Description
Discussed as an idea for demoing in-progress development efforts to external stakeholders.

# Done Critera
- [x] Request a new service to be set up for avalon-sandbox
- [x] Create new deploy for this environment
- [x] Allow access beyond IU Firewall
- [x] Choose initial branch to track
- [x] DNS (avalon-sandbox.dlib.indiana.edu, sandbox.avalonmediasystem.org)

**Comment by cjcolvar** [comment]
How about avalon-sandbox.dlib.indiana.edu?  It could be open to outside the IU network and we can switch which branch it tracks when we want to demo a new feature.  We can also bring it up and down when we want so it doesn't always have to be running.

**Comment by cjcolvar** [comment]
Request submitted: https://bugs.dlib.indiana.edu/browse/SYS-1327
