### ISSUE TITLE
Upgrade to Fedora 6

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5039]
# Description
Avalon 8.0 has Fedora 6 support as a goal. Investigation has started into Fedora 6 for Avalon 7 and Chris has been testing and fixing this—69 failing tests remain, which may only be from 1 or 2 remaining things that are wrong.

Moving away from ActiveFedora is a related but separate task.

Data migration and tooling could be difficult to deal with; there are community tools available that there should be support for.

With the Fedora 6 upgrade, do we need a reindex? It's mostly likely just a Fedora data migration and Solr will stay as-is, so this may not be needed for 8.0.

# Done Criteria
- [x] Rebase existing F6 branch and get all tests to pass #5977
- [x] Run through upgrade process #5978
- [x] Testing against Avalon running Fedora 6 #5979
- [x] Local code changes for Fedora migration tooling—contribute those upstream
- [x] How will we work with Active Fedora? Keep changes in a specific branch, create our own fork, or work on merging for a new gem release? #5985
- [x] Investigate the changes to pear trees in Fedora (does this affect us?) #5984

**Comment by joncameron** [comment]
Timebox!

**Comment by elynema** [comment]
@joncameron When Chris and I discussed, we thought it would make sense to create an epic as a place to begin fleshing out the work needed for Fedora 6 upgrade. I think we want to first try with Active Fedora, but we should probably finalize that. It would be a good conversation either for Backlog Buddies or a Swarm topic. Do you have a preference?

**Comment by joncameron** [comment]
See #5205 for more background and previous work.

**Comment by joncameron** [comment]
This can be broken into different tickets for each of the done criteria listed.
