### ISSUE TITLE
7.7 Roadmap

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5149]
# Description
Roadmapping for future releases.

# Done Criteria
- [x] Update Avalon roadmap
- [x] Create new issues for desired features and fixes
- [x] Publish roadmap to community in April
