### ISSUE TITLE
7.7 Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5644]
# Release Checklist

## Code Changes
- [x] Update code files with version number #5677
- [x] Update license headers #5647 
- [x] Tag dependency repos #5649
- [x] Update gemfile to point to those tags #5649
- [x] Merge `develop` into `staging` #5662 #5678
- [x] Merge staging into main #5683

## Application Testing
- [x] Testing (after merge to staging)

## Documentation
- [x] Update Known Issues documentation page
- [x] Update configuration documentation (any new config in 7.7?)
- [x] Update current version number on the documentation wiki
- [x] Update wiki with release notes (once the release is published on Github)

- [x] Update metadata documentation with series info (https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957954564/Metadata+Fields)
- [x] Add note to Accessibility page that Avalon application is compliant with WCAG A and AA
- [x] Test - does Series need to be added to batch manifest (update batch manifest if so)
- [x] Review Ramp documentation (in Github repo wiki).
- [x] Update transcript/supplemental file feature documentation - machine-generated transcripts and multiple captions
- [x] Create and Write Upgrade Page (7.6 -> 7.7) #5648

## Release and Documentation
- [x] Write a draft of release notes on Github
- [x] Publish release in Github (create tag as well, if the release is not already tagged)  https://github.com/avalonmediasystem/avalon/releases
- [x]  put link in release notes to Github-provided changelog (i.e. https://github.com/avalonmediasystem/avalon/compare/v.7.6...v7.7)
- [x] Build and push updated docker images (may already happen via bamboo CI process)
- [x] Update avalon-docker to point at new release docker tag and github tag; update solr service (tag, command, and storage volume to bind mount) https://github.com/avalonmediasystem/avalon-docker/issues/76
- [x] Rebuild develop from main (our git flow)
- [x] Deploy release to demo.avalonmediasystem.org - https://github.com/avalonmediasystem/avalon/issues/5700

## Website and Outreach
- [x] Publish blog post announcing the release
- [x] Update homepage with blog post for release announcement
- [x] Update homepage with the updated version and documentation links
- [x] Put announcement on Twitter
- [x] Put announcement on Facebook
- [x] Send announcement email to Samvera community mailing lists
- [x] Send announcement to avalon-l mailing list
- [x] Publicize in appropriate Slack channels

# Included PRs
- Everything in current develop branch

**Comment by joncameron** [comment]
Docker compose tag is currently to 7.x; could be an issue if people update their containers and get the latest release by default. More specific tags in the docker-compose file could help this.
