### ISSUE TITLE
investigate alternative test server setup

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#830]
Investigate whether we decommission Lancelot and move to NU test or a sysadmin hosted server at IU. 

## Done looks like
Stories are written (if needed) for new test server setup and docs are written/updated. 

## Tasks
- [ ] Investigate state of NU Test, can it be used? 
- [ ] discuss with IU sysadmin
- [ ] write stories if necessary to get new system up and running (auto pushes, etc)

**Comment by davidschober** [comment]
@mbklein we need your input. Can we get this to work like IUs test server?
