### ISSUE TITLE
Titles for Newly Created Playlist Items Only Include Media Object Title

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#982]
### Current Behavior
- Click the "Add Playlist Item" icon
- Look at the Title field. The default title is "MediaObject_Title -"

### Possible Changes to Behavior
Examples would be:
- "Parent label - track label" (idea provided by the IU Music Library)
- "track label"
- or letting this be user-defined somewhere

### Desired Behavior for Population of Title Field For New Playlist Items
- If there is only a single section and no structural metadata XML exists, use MediaObject's Title
- If no structural metadata XML exists or it exists but no structural segment is active, use "MediaObject_Title - SectionLabel"
- If structural metadata XML exists and a segment is currently highlighted, use "#{Label value of parent node if one exists} - #{Label of span which is currently active}"

### Done Looks Like
- The default _Title_ value for a playlist item is populated based on the desired behavior above.

### Real world example
The title of this playlist item defaults to the name of the media object, when it could be "Schuber, Sonata ... Track 3. Allegreto"
![screen shot 2017-01-18 at 2 25 25 pm](https://cloud.githubusercontent.com/assets/1406618/22079750/e926dd08-dd8a-11e6-81c5-e1e291246081.png)

### Tasks
- [ ] Add controller function to masterfile_controller for generating the playlist label.
- [ ] Add tests for said function
- [ ] Use function in appropriate views

**Comment by davidschober** [comment]
per @bkeese currently this is the label for the section or the media object label. Adding structural label is a new feature.

**Comment by carrickr** [comment]
Need decisions made on which prepopulation option(s) should be implemented.  Can task after that,

**Comment by davidschober** [comment]
Per discussion john and David, the default should the section title OR the label from the  currently selected structural metadata
